# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 679)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filenameLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filenameLabel.sizePolicy().hasHeightForWidth())
        self.filenameLabel.setSizePolicy(sizePolicy)
        self.filenameLabel.setObjectName("filenameLabel")
        self.verticalLayout.addWidget(self.filenameLabel)
        self.plotTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.plotTabWidget.setObjectName("plotTabWidget")
        self.wxwyvzTab = QtWidgets.QWidget()
        self.wxwyvzTab.setObjectName("wxwyvzTab")
        self.plotTabWidget.addTab(self.wxwyvzTab, "")
        self.wxvwyTab = QtWidgets.QWidget()
        self.wxvwyTab.setObjectName("wxvwyTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wxvwyTab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.wxvwyPlotWidget = QtWidgets.QWidget(self.wxvwyTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.wxvwyPlotWidget.sizePolicy().hasHeightForWidth())
        self.wxvwyPlotWidget.setSizePolicy(sizePolicy)
        self.wxvwyPlotWidget.setSizeIncrement(QtCore.QSize(1, 1))
        self.wxvwyPlotWidget.setAutoFillBackground(False)
        self.wxvwyPlotWidget.setObjectName("wxvwyPlotWidget")
        self.horizontalLayout_2.addWidget(self.wxvwyPlotWidget)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.plotTabWidget.addTab(self.wxvwyTab, "")
        self.stageTab = QtWidgets.QWidget()
        self.stageTab.setObjectName("stageTab")
        self.plotTabWidget.addTab(self.stageTab, "")
        self.verticalLayout.addWidget(self.plotTabWidget)
        self.pixFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixFrame.sizePolicy().hasHeightForWidth())
        self.pixFrame.setSizePolicy(sizePolicy)
        self.pixFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pixFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pixFrame.setObjectName("pixFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.pixFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.powerLabel = QtWidgets.QLabel(self.pixFrame)
        self.powerLabel.setObjectName("powerLabel")
        self.horizontalLayout.addWidget(self.powerLabel)
        self.powerComboBox = QtWidgets.QComboBox(self.pixFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.powerComboBox.sizePolicy().hasHeightForWidth())
        self.powerComboBox.setSizePolicy(sizePolicy)
        self.powerComboBox.setMinimumSize(QtCore.QSize(40, 0))
        self.powerComboBox.setObjectName("powerComboBox")
        self.horizontalLayout.addWidget(self.powerComboBox)
        self.pixelLabel = QtWidgets.QLabel(self.pixFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixelLabel.sizePolicy().hasHeightForWidth())
        self.pixelLabel.setSizePolicy(sizePolicy)
        self.pixelLabel.setObjectName("pixelLabel")
        self.horizontalLayout.addWidget(self.pixelLabel)
        self.pixelSpinBox = QtWidgets.QDoubleSpinBox(self.pixFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixelSpinBox.sizePolicy().hasHeightForWidth())
        self.pixelSpinBox.setSizePolicy(sizePolicy)
        self.pixelSpinBox.setMinimumSize(QtCore.QSize(80, 0))
        self.pixelSpinBox.setDecimals(1)
        self.pixelSpinBox.setMaximum(1000.0)
        self.pixelSpinBox.setSingleStep(0.1)
        self.pixelSpinBox.setObjectName("pixelSpinBox")
        self.horizontalLayout.addWidget(self.pixelSpinBox)
        self.verticalLayout.addWidget(self.pixFrame)
        self.calLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.calLineEdit.setObjectName("calLineEdit")
        self.verticalLayout.addWidget(self.calLineEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 743, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Molecule_List = QtWidgets.QAction(MainWindow)
        self.actionLoad_Molecule_List.setObjectName("actionLoad_Molecule_List")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionRedo_Fit = QtWidgets.QAction(MainWindow)
        self.actionRedo_Fit.setObjectName("actionRedo_Fit")
        self.actionSave_Calibration = QtWidgets.QAction(MainWindow)
        self.actionSave_Calibration.setObjectName("actionSave_Calibration")
        self.actionLoad_Calibration = QtWidgets.QAction(MainWindow)
        self.actionLoad_Calibration.setObjectName("actionLoad_Calibration")
        self.actionLoad_Data = QtWidgets.QAction(MainWindow)
        self.actionLoad_Data.setObjectName("actionLoad_Data")
        self.menuFile.addAction(self.actionLoad_Molecule_List)
        self.menuFile.addAction(self.actionRedo_Fit)
        self.menuFile.addAction(self.actionSave_Calibration)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Calibration)
        self.menuFile.addAction(self.actionLoad_Data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.plotTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZeeCalibrator"))
        self.filenameLabel.setText(_translate("MainWindow", "None"))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.wxwyvzTab), _translate("MainWindow", "Wx, Wy vs Z"))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.wxvwyTab), _translate("MainWindow", "Wx vs Wy"))
        self.plotTabWidget.setTabText(self.plotTabWidget.indexOf(self.stageTab), _translate("MainWindow", "Stage Calibration"))
        self.powerLabel.setText(_translate("MainWindow", "Fit Power:"))
        self.pixelLabel.setText(_translate("MainWindow", "Pixels Per Nanometer:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Molecule_List.setText(_translate("MainWindow", "Load Molecule List"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionRedo_Fit.setText(_translate("MainWindow", "Redo Fit"))
        self.actionSave_Calibration.setText(_translate("MainWindow", "Save Calibration"))
        self.actionLoad_Calibration.setText(_translate("MainWindow", "Load Calibration"))
        self.actionLoad_Data.setText(_translate("MainWindow", "Load Data"))

