# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fluidics_control.ui'
#
# Created: Thu Dec 19 18:07:38 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(652, 703)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.valve1Box = QtGui.QGroupBox(self.centralwidget)
        self.valve1Box.setGeometry(QtCore.QRect(10, 360, 163, 185))
        self.valve1Box.setObjectName(_fromUtf8("valve1Box"))
        self.verticalLayout = QtGui.QVBoxLayout(self.valve1Box)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.valve1StatusLabel = QtGui.QLabel(self.valve1Box)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.valve1StatusLabel.setFont(font)
        self.valve1StatusLabel.setObjectName(_fromUtf8("valve1StatusLabel"))
        self.verticalLayout.addWidget(self.valve1StatusLabel)
        self.valve1PositionLabel = QtGui.QLabel(self.valve1Box)
        self.valve1PositionLabel.setObjectName(_fromUtf8("valve1PositionLabel"))
        self.verticalLayout.addWidget(self.valve1PositionLabel)
        self.valve1desiredPosition = QtGui.QComboBox(self.valve1Box)
        self.valve1desiredPosition.setObjectName(_fromUtf8("valve1desiredPosition"))
        self.valve1desiredPosition.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.valve1desiredPosition)
        self.valve1RotationDirection = QtGui.QLabel(self.valve1Box)
        self.valve1RotationDirection.setObjectName(_fromUtf8("valve1RotationDirection"))
        self.verticalLayout.addWidget(self.valve1RotationDirection)
        self.valve1desiredDirection = QtGui.QComboBox(self.valve1Box)
        self.valve1desiredDirection.setObjectName(_fromUtf8("valve1desiredDirection"))
        self.valve1desiredDirection.addItem(_fromUtf8(""))
        self.valve1desiredDirection.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.valve1desiredDirection)
        self.valve1Move = QtGui.QPushButton(self.valve1Box)
        self.valve1Move.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.valve1Move.setObjectName(_fromUtf8("valve1Move"))
        self.verticalLayout.addWidget(self.valve1Move)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.valve2Box = QtGui.QGroupBox(self.centralwidget)
        self.valve2Box.setGeometry(QtCore.QRect(180, 360, 163, 185))
        self.valve2Box.setObjectName(_fromUtf8("valve2Box"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.valve2Box)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.valve2Box)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.valve2Box)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.comboBox_3 = QtGui.QComboBox(self.valve2Box)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBox_3)
        self.label_6 = QtGui.QLabel(self.valve2Box)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.comboBox_4 = QtGui.QComboBox(self.valve2Box)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBox_4)
        self.pushButton_2 = QtGui.QPushButton(self.valve2Box)
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_2.addWidget(self.pushButton_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.valve3Box = QtGui.QGroupBox(self.centralwidget)
        self.valve3Box.setGeometry(QtCore.QRect(350, 360, 163, 185))
        self.valve3Box.setObjectName(_fromUtf8("valve3Box"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.valve3Box)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_7 = QtGui.QLabel(self.valve3Box)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.valve3Box)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.comboBox_5 = QtGui.QComboBox(self.valve3Box)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_5)
        self.label_9 = QtGui.QLabel(self.valve3Box)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.comboBox_6 = QtGui.QComboBox(self.valve3Box)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_6)
        self.pushButton_3 = QtGui.QPushButton(self.valve3Box)
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_3.addWidget(self.pushButton_3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 652, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRecipes = QtGui.QMenu(self.menubar)
        self.menuRecipes.setObjectName(_fromUtf8("menuRecipes"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionInitialize_Hamilton = QtGui.QAction(MainWindow)
        self.actionInitialize_Hamilton.setObjectName(_fromUtf8("actionInitialize_Hamilton"))
        self.actionLoadXMLRecipe = QtGui.QAction(MainWindow)
        self.actionLoadXMLRecipe.setObjectName(_fromUtf8("actionLoadXMLRecipe"))
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionInitialize_Hamilton)
        self.menuRecipes.addAction(self.actionLoadXMLRecipe)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRecipes.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.valve1Box.setTitle(_translate("MainWindow", "Valve 1: a", None))
        self.valve1StatusLabel.setText(_translate("MainWindow", "Valve Status", None))
        self.valve1PositionLabel.setText(_translate("MainWindow", "Valve Position", None))
        self.valve1desiredPosition.setItemText(0, _translate("MainWindow", "Position 1", None))
        self.valve1RotationDirection.setText(_translate("MainWindow", "Rotation Direction", None))
        self.valve1desiredDirection.setItemText(0, _translate("MainWindow", "Clockwise", None))
        self.valve1desiredDirection.setItemText(1, _translate("MainWindow", "Counter Clockwise", None))
        self.valve1Move.setText(_translate("MainWindow", "Move Valve", None))
        self.valve2Box.setTitle(_translate("MainWindow", "Valve 2: a", None))
        self.label_4.setText(_translate("MainWindow", "Valve Status", None))
        self.label_5.setText(_translate("MainWindow", "Valve Position", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Position 1", None))
        self.label_6.setText(_translate("MainWindow", "Rotation Direction", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Clockwise", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Counter Clockwise", None))
        self.pushButton_2.setText(_translate("MainWindow", "Move Valve", None))
        self.valve3Box.setTitle(_translate("MainWindow", "Valve 2: a", None))
        self.label_7.setText(_translate("MainWindow", "Valve Status", None))
        self.label_8.setText(_translate("MainWindow", "Valve Position", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Position 1", None))
        self.label_9.setText(_translate("MainWindow", "Rotation Direction", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Clockwise", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Counter Clockwise", None))
        self.pushButton_3.setText(_translate("MainWindow", "Move Valve", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuRecipes.setTitle(_translate("MainWindow", "Recipes", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionInitialize_Hamilton.setText(_translate("MainWindow", "Initialize Hamilton", None))
        self.actionLoadXMLRecipe.setText(_translate("MainWindow", "Load XML Recipe", None))

