# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dave.ui'
#
# Created: Sat Apr 12 08:21:49 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(592, 723)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(590, 500))
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mainGridLayout = QtGui.QGridLayout(self.centralwidget)
        self.mainGridLayout.setObjectName(_fromUtf8("mainGridLayout"))
        self.estimatesGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.estimatesGroupBox.setObjectName(_fromUtf8("estimatesGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.estimatesGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.spaceLabel = QtGui.QLabel(self.estimatesGroupBox)
        self.spaceLabel.setObjectName(_fromUtf8("spaceLabel"))
        self.verticalLayout_2.addWidget(self.spaceLabel)
        self.timeLabel = QtGui.QLabel(self.estimatesGroupBox)
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.verticalLayout_2.addWidget(self.timeLabel)
        self.mainGridLayout.addWidget(self.estimatesGroupBox, 2, 6, 1, 1)
        self.runButton = QtGui.QPushButton(self.centralwidget)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.mainGridLayout.addWidget(self.runButton, 7, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.mainGridLayout.addItem(spacerItem, 4, 6, 1, 1)
        self.abortButton = QtGui.QPushButton(self.centralwidget)
        self.abortButton.setObjectName(_fromUtf8("abortButton"))
        self.mainGridLayout.addWidget(self.abortButton, 7, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.mainGridLayout.addItem(spacerItem1, 7, 4, 1, 1)
        self.notificationGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.notificationGroupBox.setObjectName(_fromUtf8("notificationGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.notificationGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.fromAddressLineEdit = QtGui.QLineEdit(self.notificationGroupBox)
        self.fromAddressLineEdit.setObjectName(_fromUtf8("fromAddressLineEdit"))
        self.gridLayout.addWidget(self.fromAddressLineEdit, 3, 0, 1, 3)
        self.fromPasswordLabel = QtGui.QLabel(self.notificationGroupBox)
        self.fromPasswordLabel.setObjectName(_fromUtf8("fromPasswordLabel"))
        self.gridLayout.addWidget(self.fromPasswordLabel, 4, 0, 1, 3)
        self.errorMsgCheckBox = QtGui.QCheckBox(self.notificationGroupBox)
        self.errorMsgCheckBox.setObjectName(_fromUtf8("errorMsgCheckBox"))
        self.gridLayout.addWidget(self.errorMsgCheckBox, 8, 0, 1, 1)
        self.statusMsgCheckBox = QtGui.QCheckBox(self.notificationGroupBox)
        self.statusMsgCheckBox.setObjectName(_fromUtf8("statusMsgCheckBox"))
        self.gridLayout.addWidget(self.statusMsgCheckBox, 9, 0, 1, 1)
        self.frequencyLabel = QtGui.QLabel(self.notificationGroupBox)
        self.frequencyLabel.setObjectName(_fromUtf8("frequencyLabel"))
        self.gridLayout.addWidget(self.frequencyLabel, 9, 1, 1, 1)
        self.frequencySpinBox = QtGui.QSpinBox(self.notificationGroupBox)
        self.frequencySpinBox.setObjectName(_fromUtf8("frequencySpinBox"))
        self.gridLayout.addWidget(self.frequencySpinBox, 9, 2, 1, 1)
        self.toAddressLabel = QtGui.QLabel(self.notificationGroupBox)
        self.toAddressLabel.setObjectName(_fromUtf8("toAddressLabel"))
        self.gridLayout.addWidget(self.toAddressLabel, 6, 0, 1, 3)
        self.smtpServerLabel = QtGui.QLabel(self.notificationGroupBox)
        self.smtpServerLabel.setObjectName(_fromUtf8("smtpServerLabel"))
        self.gridLayout.addWidget(self.smtpServerLabel, 0, 0, 1, 3)
        self.fromAddressLabel = QtGui.QLabel(self.notificationGroupBox)
        self.fromAddressLabel.setObjectName(_fromUtf8("fromAddressLabel"))
        self.gridLayout.addWidget(self.fromAddressLabel, 2, 0, 1, 3)
        self.smtpServerLineEdit = QtGui.QLineEdit(self.notificationGroupBox)
        self.smtpServerLineEdit.setText(_fromUtf8(""))
        self.smtpServerLineEdit.setObjectName(_fromUtf8("smtpServerLineEdit"))
        self.gridLayout.addWidget(self.smtpServerLineEdit, 1, 0, 1, 3)
        self.fromPasswordLineEdit = QtGui.QLineEdit(self.notificationGroupBox)
        self.fromPasswordLineEdit.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.fromPasswordLineEdit.setObjectName(_fromUtf8("fromPasswordLineEdit"))
        self.gridLayout.addWidget(self.fromPasswordLineEdit, 5, 0, 1, 3)
        self.toAddressLineEdit = QtGui.QLineEdit(self.notificationGroupBox)
        self.toAddressLineEdit.setObjectName(_fromUtf8("toAddressLineEdit"))
        self.gridLayout.addWidget(self.toAddressLineEdit, 7, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 10, 0, 1, 1)
        self.mainGridLayout.addWidget(self.notificationGroupBox, 1, 6, 1, 1)
        self.sequenceGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.sequenceGroupBox.setObjectName(_fromUtf8("sequenceGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.sequenceGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.sequenceLabel = QtGui.QLabel(self.sequenceGroupBox)
        self.sequenceLabel.setObjectName(_fromUtf8("sequenceLabel"))
        self.verticalLayout.addWidget(self.sequenceLabel)
        self.mainGridLayout.addWidget(self.sequenceGroupBox, 0, 1, 1, 6)
        self.commandGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.commandGroupBox.setObjectName(_fromUtf8("commandGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.commandGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.commandSequenceLabel = QtGui.QLabel(self.commandGroupBox)
        self.commandSequenceLabel.setObjectName(_fromUtf8("commandSequenceLabel"))
        self.verticalLayout_3.addWidget(self.commandSequenceLabel)
        self.commandSequenceList = QtGui.QListWidget(self.commandGroupBox)
        self.commandSequenceList.setObjectName(_fromUtf8("commandSequenceList"))
        self.verticalLayout_3.addWidget(self.commandSequenceList)
        self.selectCommandButton = QtGui.QPushButton(self.commandGroupBox)
        self.selectCommandButton.setObjectName(_fromUtf8("selectCommandButton"))
        self.verticalLayout_3.addWidget(self.selectCommandButton)
        self.commandDetailLabel = QtGui.QLabel(self.commandGroupBox)
        self.commandDetailLabel.setObjectName(_fromUtf8("commandDetailLabel"))
        self.verticalLayout_3.addWidget(self.commandDetailLabel)
        self.commandDetailsTable = QtGui.QTableWidget(self.commandGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.commandDetailsTable.setFont(font)
        self.commandDetailsTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.commandDetailsTable.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.commandDetailsTable.setShowGrid(False)
        self.commandDetailsTable.setWordWrap(False)
        self.commandDetailsTable.setObjectName(_fromUtf8("commandDetailsTable"))
        self.commandDetailsTable.setColumnCount(0)
        self.commandDetailsTable.setRowCount(0)
        self.commandDetailsTable.horizontalHeader().setVisible(False)
        self.commandDetailsTable.horizontalHeader().setMinimumSectionSize(18)
        self.commandDetailsTable.verticalHeader().setVisible(False)
        self.commandDetailsTable.verticalHeader().setDefaultSectionSize(18)
        self.commandDetailsTable.verticalHeader().setMinimumSectionSize(18)
        self.verticalLayout_3.addWidget(self.commandDetailsTable)
        self.currentCommandGroupBox = QtGui.QGroupBox(self.commandGroupBox)
        self.currentCommandGroupBox.setObjectName(_fromUtf8("currentCommandGroupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.currentCommandGroupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.currentCommand = QtGui.QLabel(self.currentCommandGroupBox)
        self.currentCommand.setObjectName(_fromUtf8("currentCommand"))
        self.verticalLayout_5.addWidget(self.currentCommand)
        self.verticalLayout_3.addWidget(self.currentCommandGroupBox)
        self.progressBarLabel = QtGui.QLabel(self.commandGroupBox)
        self.progressBarLabel.setObjectName(_fromUtf8("progressBarLabel"))
        self.verticalLayout_3.addWidget(self.progressBarLabel)
        self.progressBar = QtGui.QProgressBar(self.commandGroupBox)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_3.addWidget(self.progressBar)
        self.mainGridLayout.addWidget(self.commandGroupBox, 1, 1, 4, 4)
        self.validateSequenceButton = QtGui.QPushButton(self.centralwidget)
        self.validateSequenceButton.setObjectName(_fromUtf8("validateSequenceButton"))
        self.mainGridLayout.addWidget(self.validateSequenceButton, 7, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 592, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuXML = QtGui.QMenu(self.menubar)
        self.menuXML.setObjectName(_fromUtf8("menuXML"))
        self.menuNotifications = QtGui.QMenu(self.menubar)
        self.menuNotifications.setObjectName(_fromUtf8("menuNotifications"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Sequence = QtGui.QAction(MainWindow)
        self.actionNew_Sequence.setObjectName(_fromUtf8("actionNew_Sequence"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionGenerate = QtGui.QAction(MainWindow)
        self.actionGenerate.setObjectName(_fromUtf8("actionGenerate"))
        self.actionGenerateXML = QtGui.QAction(MainWindow)
        self.actionGenerateXML.setObjectName(_fromUtf8("actionGenerateXML"))
        self.actionSendTestEmail = QtGui.QAction(MainWindow)
        self.actionSendTestEmail.setObjectName(_fromUtf8("actionSendTestEmail"))
        self.menuFile.addAction(self.actionNew_Sequence)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuXML.addAction(self.actionGenerateXML)
        self.menuNotifications.addAction(self.actionSendTestEmail)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuXML.menuAction())
        self.menubar.addAction(self.menuNotifications.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Dave", None))
        self.estimatesGroupBox.setTitle(_translate("MainWindow", "Estimates", None))
        self.spaceLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.timeLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.runButton.setText(_translate("MainWindow", "Run", None))
        self.abortButton.setText(_translate("MainWindow", "Abort", None))
        self.notificationGroupBox.setTitle(_translate("MainWindow", "Notifications", None))
        self.fromPasswordLabel.setText(_translate("MainWindow", "From password:", None))
        self.errorMsgCheckBox.setText(_translate("MainWindow", "e-mail error messages", None))
        self.statusMsgCheckBox.setText(_translate("MainWindow", "e-mail status messages", None))
        self.frequencyLabel.setText(_translate("MainWindow", "Frequency:", None))
        self.toAddressLabel.setText(_translate("MainWindow", "To address:", None))
        self.smtpServerLabel.setText(_translate("MainWindow", "SMTP server:", None))
        self.fromAddressLabel.setText(_translate("MainWindow", "From address:", None))
        self.sequenceGroupBox.setTitle(_translate("MainWindow", "Sequence File", None))
        self.sequenceLabel.setText(_translate("MainWindow", "NA", None))
        self.commandGroupBox.setTitle(_translate("MainWindow", "Sequence Details", None))
        self.commandSequenceLabel.setText(_translate("MainWindow", "Command Sequence", None))
        self.selectCommandButton.setText(_translate("MainWindow", "Select Command", None))
        self.commandDetailLabel.setText(_translate("MainWindow", "Command Details", None))
        self.currentCommandGroupBox.setTitle(_translate("MainWindow", "Current Command", None))
        self.currentCommand.setText(_translate("MainWindow", "Command Details", None))
        self.progressBarLabel.setText(_translate("MainWindow", "Sequence Progress", None))
        self.validateSequenceButton.setText(_translate("MainWindow", "Validate", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuXML.setTitle(_translate("MainWindow", "XML", None))
        self.menuNotifications.setTitle(_translate("MainWindow", "Notifications", None))
        self.actionNew_Sequence.setText(_translate("MainWindow", "Load Sequence", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionGenerate.setText(_translate("MainWindow", "Generate (Version 1.0)", None))
        self.actionGenerateXML.setText(_translate("MainWindow", "Generate XML", None))
        self.actionSendTestEmail.setText(_translate("MainWindow", "Send Test Email", None))

