# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dave.ui'
#
# Created: Fri Nov 22 08:41:13 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(590, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(590, 500))
        MainWindow.setMaximumSize(QtCore.QSize(590, 500))
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.movieGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.movieGroupBox.setGeometry(QtCore.QRect(10, 10, 271, 291))
        self.movieGroupBox.setObjectName(_fromUtf8("movieGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.movieGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.movieTableWidget = QtGui.QTableWidget(self.movieGroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.movieTableWidget.setFont(font)
        self.movieTableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.movieTableWidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.movieTableWidget.setShowGrid(False)
        self.movieTableWidget.setWordWrap(False)
        self.movieTableWidget.setObjectName(_fromUtf8("movieTableWidget"))
        self.movieTableWidget.setColumnCount(0)
        self.movieTableWidget.setRowCount(0)
        self.movieTableWidget.horizontalHeader().setVisible(False)
        self.movieTableWidget.horizontalHeader().setMinimumSectionSize(18)
        self.movieTableWidget.verticalHeader().setVisible(False)
        self.movieTableWidget.verticalHeader().setDefaultSectionSize(18)
        self.movieTableWidget.verticalHeader().setMinimumSectionSize(18)
        self.gridLayout.addWidget(self.movieTableWidget, 0, 0, 1, 1)
        self.runButton = QtGui.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(10, 410, 91, 24))
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.notificationGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.notificationGroupBox.setGeometry(QtCore.QRect(290, 10, 291, 291))
        self.notificationGroupBox.setObjectName(_fromUtf8("notificationGroupBox"))
        self.smtpServerLineEdit = QtGui.QLineEdit(self.notificationGroupBox)
        self.smtpServerLineEdit.setGeometry(QtCore.QRect(20, 40, 261, 20))
        self.smtpServerLineEdit.setObjectName(_fromUtf8("smtpServerLineEdit"))
        self.smtpServerLabel = QtGui.QLabel(self.notificationGroupBox)
        self.smtpServerLabel.setGeometry(QtCore.QRect(10, 20, 271, 16))
        self.smtpServerLabel.setObjectName(_fromUtf8("smtpServerLabel"))
        self.fromAddressLabel = QtGui.QLabel(self.notificationGroupBox)
        self.fromAddressLabel.setGeometry(QtCore.QRect(10, 70, 271, 16))
        self.fromAddressLabel.setObjectName(_fromUtf8("fromAddressLabel"))
        self.fromAddressLineEdit = QtGui.QLineEdit(self.notificationGroupBox)
        self.fromAddressLineEdit.setGeometry(QtCore.QRect(20, 90, 261, 20))
        self.fromAddressLineEdit.setObjectName(_fromUtf8("fromAddressLineEdit"))
        self.fromPasswordLabel = QtGui.QLabel(self.notificationGroupBox)
        self.fromPasswordLabel.setGeometry(QtCore.QRect(10, 120, 271, 16))
        self.fromPasswordLabel.setObjectName(_fromUtf8("fromPasswordLabel"))
        self.fromPasswordLineEdit = QtGui.QLineEdit(self.notificationGroupBox)
        self.fromPasswordLineEdit.setGeometry(QtCore.QRect(20, 140, 261, 20))
        self.fromPasswordLineEdit.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.fromPasswordLineEdit.setObjectName(_fromUtf8("fromPasswordLineEdit"))
        self.toAddressLabel = QtGui.QLabel(self.notificationGroupBox)
        self.toAddressLabel.setGeometry(QtCore.QRect(10, 170, 271, 16))
        self.toAddressLabel.setObjectName(_fromUtf8("toAddressLabel"))
        self.toAddressLineEdit = QtGui.QLineEdit(self.notificationGroupBox)
        self.toAddressLineEdit.setGeometry(QtCore.QRect(20, 190, 261, 20))
        self.toAddressLineEdit.setObjectName(_fromUtf8("toAddressLineEdit"))
        self.errorMsgCheckBox = QtGui.QCheckBox(self.notificationGroupBox)
        self.errorMsgCheckBox.setGeometry(QtCore.QRect(10, 220, 141, 17))
        self.errorMsgCheckBox.setObjectName(_fromUtf8("errorMsgCheckBox"))
        self.statusMsgCheckBox = QtGui.QCheckBox(self.notificationGroupBox)
        self.statusMsgCheckBox.setGeometry(QtCore.QRect(10, 250, 141, 17))
        self.statusMsgCheckBox.setObjectName(_fromUtf8("statusMsgCheckBox"))
        self.frequencySpinBox = QtGui.QSpinBox(self.notificationGroupBox)
        self.frequencySpinBox.setGeometry(QtCore.QRect(210, 249, 71, 22))
        self.frequencySpinBox.setObjectName(_fromUtf8("frequencySpinBox"))
        self.frequencyLabel = QtGui.QLabel(self.notificationGroupBox)
        self.frequencyLabel.setGeometry(QtCore.QRect(150, 249, 71, 20))
        self.frequencyLabel.setObjectName(_fromUtf8("frequencyLabel"))
        self.abortButton = QtGui.QPushButton(self.centralwidget)
        self.abortButton.setGeometry(QtCore.QRect(490, 410, 91, 24))
        self.abortButton.setObjectName(_fromUtf8("abortButton"))
        self.estimatesGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.estimatesGroupBox.setGeometry(QtCore.QRect(10, 350, 571, 51))
        self.estimatesGroupBox.setObjectName(_fromUtf8("estimatesGroupBox"))
        self.timeLabel = QtGui.QLabel(self.estimatesGroupBox)
        self.timeLabel.setGeometry(QtCore.QRect(10, 20, 251, 20))
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.spaceLabel = QtGui.QLabel(self.estimatesGroupBox)
        self.spaceLabel.setGeometry(QtCore.QRect(270, 20, 291, 20))
        self.spaceLabel.setObjectName(_fromUtf8("spaceLabel"))
        self.sequenceGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.sequenceGroupBox.setGeometry(QtCore.QRect(10, 300, 571, 51))
        self.sequenceGroupBox.setObjectName(_fromUtf8("sequenceGroupBox"))
        self.sequenceLabel = QtGui.QLabel(self.sequenceGroupBox)
        self.sequenceLabel.setGeometry(QtCore.QRect(10, 20, 551, 21))
        self.sequenceLabel.setObjectName(_fromUtf8("sequenceLabel"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuXML = QtGui.QMenu(self.menubar)
        self.menuXML.setObjectName(_fromUtf8("menuXML"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Sequence = QtGui.QAction(MainWindow)
        self.actionNew_Sequence.setObjectName(_fromUtf8("actionNew_Sequence"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionGenerate = QtGui.QAction(MainWindow)
        self.actionGenerate.setObjectName(_fromUtf8("actionGenerate"))
        self.menuFile.addAction(self.actionNew_Sequence)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuXML.addAction(self.actionGenerate)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuXML.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Dave", None))
        self.movieGroupBox.setTitle(_translate("MainWindow", "Movie Details", None))
        self.runButton.setText(_translate("MainWindow", "Run", None))
        self.notificationGroupBox.setTitle(_translate("MainWindow", "Notifications", None))
        self.smtpServerLabel.setText(_translate("MainWindow", "SMTP server:", None))
        self.fromAddressLabel.setText(_translate("MainWindow", "From address:", None))
        self.fromPasswordLabel.setText(_translate("MainWindow", "From password:", None))
        self.toAddressLabel.setText(_translate("MainWindow", "To address:", None))
        self.errorMsgCheckBox.setText(_translate("MainWindow", "e-mail error messages", None))
        self.statusMsgCheckBox.setText(_translate("MainWindow", "e-mail status messages", None))
        self.frequencyLabel.setText(_translate("MainWindow", "Frequency:", None))
        self.abortButton.setText(_translate("MainWindow", "Abort", None))
        self.estimatesGroupBox.setTitle(_translate("MainWindow", "Estimates", None))
        self.timeLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.spaceLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.sequenceGroupBox.setTitle(_translate("MainWindow", "Sequence", None))
        self.sequenceLabel.setText(_translate("MainWindow", "NA", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuXML.setTitle(_translate("MainWindow", "XML", None))
        self.actionNew_Sequence.setText(_translate("MainWindow", "New Sequence", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionGenerate.setText(_translate("MainWindow", "Generate", None))

