# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera-params-detached.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(451, 72)
        GroupBox.setMinimumSize(QtCore.QSize(414, 0))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(GroupBox)
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exposureTimeLabel = QtWidgets.QLabel(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureTimeLabel.sizePolicy().hasHeightForWidth())
        self.exposureTimeLabel.setSizePolicy(sizePolicy)
        self.exposureTimeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.exposureTimeLabel.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.exposureTimeLabel.setObjectName("exposureTimeLabel")
        self.horizontalLayout.addWidget(self.exposureTimeLabel)
        self.exposureTimeText = QtWidgets.QLabel(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureTimeText.sizePolicy().hasHeightForWidth())
        self.exposureTimeText.setSizePolicy(sizePolicy)
        self.exposureTimeText.setMinimumSize(QtCore.QSize(50, 0))
        self.exposureTimeText.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.exposureTimeText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exposureTimeText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.exposureTimeText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exposureTimeText.setObjectName("exposureTimeText")
        self.horizontalLayout.addWidget(self.exposureTimeText)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.FPSLabel = QtWidgets.QLabel(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FPSLabel.sizePolicy().hasHeightForWidth())
        self.FPSLabel.setSizePolicy(sizePolicy)
        self.FPSLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.FPSLabel.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.FPSLabel.setObjectName("FPSLabel")
        self.horizontalLayout_4.addWidget(self.FPSLabel)
        self.FPSText = QtWidgets.QLabel(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FPSText.sizePolicy().hasHeightForWidth())
        self.FPSText.setSizePolicy(sizePolicy)
        self.FPSText.setMinimumSize(QtCore.QSize(50, 0))
        self.FPSText.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.FPSText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.FPSText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FPSText.setObjectName("FPSText")
        self.horizontalLayout_4.addWidget(self.FPSText)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pictureSizeLabel = QtWidgets.QLabel(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pictureSizeLabel.sizePolicy().hasHeightForWidth())
        self.pictureSizeLabel.setSizePolicy(sizePolicy)
        self.pictureSizeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.pictureSizeLabel.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.pictureSizeLabel.setObjectName("pictureSizeLabel")
        self.horizontalLayout_6.addWidget(self.pictureSizeLabel)
        self.pictureSizeText = QtWidgets.QLabel(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pictureSizeText.sizePolicy().hasHeightForWidth())
        self.pictureSizeText.setSizePolicy(sizePolicy)
        self.pictureSizeText.setMinimumSize(QtCore.QSize(90, 0))
        self.pictureSizeText.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.pictureSizeText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pictureSizeText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pictureSizeText.setObjectName("pictureSizeText")
        self.horizontalLayout_6.addWidget(self.pictureSizeText)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.temperatureLabel = QtWidgets.QLabel(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperatureLabel.sizePolicy().hasHeightForWidth())
        self.temperatureLabel.setSizePolicy(sizePolicy)
        self.temperatureLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.temperatureLabel.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.horizontalLayout_2.addWidget(self.temperatureLabel)
        self.temperatureText = QtWidgets.QLabel(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperatureText.sizePolicy().hasHeightForWidth())
        self.temperatureText.setSizePolicy(sizePolicy)
        self.temperatureText.setMinimumSize(QtCore.QSize(50, 0))
        self.temperatureText.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.temperatureText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.temperatureText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temperatureText.setObjectName("temperatureText")
        self.horizontalLayout_2.addWidget(self.temperatureText)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.EMCCDLabel = QtWidgets.QLabel(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EMCCDLabel.sizePolicy().hasHeightForWidth())
        self.EMCCDLabel.setSizePolicy(sizePolicy)
        self.EMCCDLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.EMCCDLabel.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.EMCCDLabel.setObjectName("EMCCDLabel")
        self.horizontalLayout_3.addWidget(self.EMCCDLabel)
        self.EMCCDSlider = QtWidgets.QSlider(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EMCCDSlider.sizePolicy().hasHeightForWidth())
        self.EMCCDSlider.setSizePolicy(sizePolicy)
        self.EMCCDSlider.setMinimumSize(QtCore.QSize(100, 0))
        self.EMCCDSlider.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.EMCCDSlider.setMaximum(100)
        self.EMCCDSlider.setProperty("value", 0)
        self.EMCCDSlider.setOrientation(QtCore.Qt.Horizontal)
        self.EMCCDSlider.setObjectName("EMCCDSlider")
        self.horizontalLayout_3.addWidget(self.EMCCDSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.preampGainLabel = QtWidgets.QLabel(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preampGainLabel.sizePolicy().hasHeightForWidth())
        self.preampGainLabel.setSizePolicy(sizePolicy)
        self.preampGainLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.preampGainLabel.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.preampGainLabel.setObjectName("preampGainLabel")
        self.horizontalLayout_5.addWidget(self.preampGainLabel)
        self.preampGainText = QtWidgets.QLabel(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preampGainText.sizePolicy().hasHeightForWidth())
        self.preampGainText.setSizePolicy(sizePolicy)
        self.preampGainText.setMinimumSize(QtCore.QSize(50, 0))
        self.preampGainText.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.preampGainText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.preampGainText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.preampGainText.setObjectName("preampGainText")
        self.horizontalLayout_5.addWidget(self.preampGainText)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
        GroupBox.setTitle(_translate("GroupBox", "Camera"))
        self.exposureTimeLabel.setText(_translate("GroupBox", "Exposure Time (s):"))
        self.exposureTimeText.setText(_translate("GroupBox", "0"))
        self.FPSLabel.setText(_translate("GroupBox", "FPS (Hz):"))
        self.FPSText.setText(_translate("GroupBox", "0"))
        self.pictureSizeLabel.setText(_translate("GroupBox", "Picture Size:"))
        self.pictureSizeText.setText(_translate("GroupBox", "0"))
        self.temperatureLabel.setText(_translate("GroupBox", "Temperature (C):"))
        self.temperatureText.setText(_translate("GroupBox", "0"))
        self.EMCCDLabel.setText(_translate("GroupBox", "EMCCD Gain: 0"))
        self.preampGainLabel.setText(_translate("GroupBox", "Preamp Gain:"))
        self.preampGainText.setText(_translate("GroupBox", "0"))

