# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera-display.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(645, 551)
        Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.displayWidget = QtWidgets.QWidget(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayWidget.sizePolicy().hasHeightForWidth())
        self.displayWidget.setSizePolicy(sizePolicy)
        self.displayWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.displayWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.displayWidget.setObjectName("displayWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.displayWidget)
        self.horizontalLayout_2.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cameraGraphicsView = QtCameraGraphicsView(self.displayWidget)
        self.cameraGraphicsView.setMinimumSize(QtCore.QSize(520, 520))
        self.cameraGraphicsView.setObjectName("cameraGraphicsView")
        self.horizontalLayout_2.addWidget(self.cameraGraphicsView)
        self.scaleWidget = QtWidgets.QWidget(self.displayWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleWidget.sizePolicy().hasHeightForWidth())
        self.scaleWidget.setSizePolicy(sizePolicy)
        self.scaleWidget.setMinimumSize(QtCore.QSize(70, 0))
        self.scaleWidget.setMaximumSize(QtCore.QSize(70, 16777215))
        self.scaleWidget.setObjectName("scaleWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scaleWidget)
        self.verticalLayout.setContentsMargins(0, 6, 0, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scaleMax = QtWidgets.QLabel(self.scaleWidget)
        self.scaleMax.setMaximumSize(QtCore.QSize(16777215, 14))
        self.scaleMax.setAlignment(QtCore.Qt.AlignCenter)
        self.scaleMax.setObjectName("scaleMax")
        self.verticalLayout.addWidget(self.scaleMax)
        self.slideWidget = QtWidgets.QWidget(self.scaleWidget)
        self.slideWidget.setObjectName("slideWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.slideWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rangeSliderWidget = QtWidgets.QWidget(self.slideWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeSliderWidget.sizePolicy().hasHeightForWidth())
        self.rangeSliderWidget.setSizePolicy(sizePolicy)
        self.rangeSliderWidget.setMinimumSize(QtCore.QSize(26, 0))
        self.rangeSliderWidget.setMaximumSize(QtCore.QSize(26, 16777215))
        self.rangeSliderWidget.setObjectName("rangeSliderWidget")
        self.horizontalLayout.addWidget(self.rangeSliderWidget)
        self.colorFrame = QtWidgets.QFrame(self.slideWidget)
        self.colorFrame.setMinimumSize(QtCore.QSize(20, 0))
        self.colorFrame.setMaximumSize(QtCore.QSize(20, 10000))
        self.colorFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.colorFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.colorFrame.setObjectName("colorFrame")
        self.horizontalLayout.addWidget(self.colorFrame)
        self.verticalLayout.addWidget(self.slideWidget)
        self.scaleMin = QtWidgets.QLabel(self.scaleWidget)
        self.scaleMin.setMaximumSize(QtCore.QSize(16777215, 14))
        self.scaleMin.setAlignment(QtCore.Qt.AlignCenter)
        self.scaleMin.setObjectName("scaleMin")
        self.verticalLayout.addWidget(self.scaleMin)
        self.horizontalLayout_2.addWidget(self.scaleWidget)
        self.verticalLayout_2.addWidget(self.displayWidget)
        self.infoWidget = QtWidgets.QWidget(Frame)
        self.infoWidget.setObjectName("infoWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.infoWidget)
        self.horizontalLayout_3.setContentsMargins(9, 2, 9, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.recordButton = QtRecordButton(self.infoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordButton.sizePolicy().hasHeightForWidth())
        self.recordButton.setSizePolicy(sizePolicy)
        self.recordButton.setMinimumSize(QtCore.QSize(60, 0))
        self.recordButton.setMaximumSize(QtCore.QSize(75, 23))
        self.recordButton.setObjectName("recordButton")
        self.horizontalLayout_3.addWidget(self.recordButton)
        self.shutterButton = QtShutterButton(self.infoWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shutterButton.sizePolicy().hasHeightForWidth())
        self.shutterButton.setSizePolicy(sizePolicy)
        self.shutterButton.setMinimumSize(QtCore.QSize(90, 0))
        self.shutterButton.setMaximumSize(QtCore.QSize(75, 23))
        self.shutterButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shutterButton.setObjectName("shutterButton")
        self.horizontalLayout_3.addWidget(self.shutterButton)
        self.feedComboBox = QtWidgets.QComboBox(self.infoWidget)
        self.feedComboBox.setObjectName("feedComboBox")
        self.horizontalLayout_3.addWidget(self.feedComboBox)
        spacerItem = QtWidgets.QSpacerItem(185, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.intensityPosLabel = QtWidgets.QLabel(self.infoWidget)
        self.intensityPosLabel.setMinimumSize(QtCore.QSize(61, 0))
        self.intensityPosLabel.setMaximumSize(QtCore.QSize(61, 16777215))
        self.intensityPosLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.intensityPosLabel.setObjectName("intensityPosLabel")
        self.horizontalLayout_3.addWidget(self.intensityPosLabel)
        self.intensityIntLabel = QtWidgets.QLabel(self.infoWidget)
        self.intensityIntLabel.setMinimumSize(QtCore.QSize(41, 0))
        self.intensityIntLabel.setMaximumSize(QtCore.QSize(41, 16777215))
        self.intensityIntLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.intensityIntLabel.setObjectName("intensityIntLabel")
        self.horizontalLayout_3.addWidget(self.intensityIntLabel)
        self.syncLabel = QtWidgets.QLabel(self.infoWidget)
        self.syncLabel.setMinimumSize(QtCore.QSize(41, 0))
        self.syncLabel.setMaximumSize(QtCore.QSize(41, 16777215))
        self.syncLabel.setObjectName("syncLabel")
        self.horizontalLayout_3.addWidget(self.syncLabel)
        self.syncSpinBox = QtWidgets.QSpinBox(self.infoWidget)
        self.syncSpinBox.setMinimumSize(QtCore.QSize(46, 0))
        self.syncSpinBox.setMaximumSize(QtCore.QSize(46, 16777215))
        self.syncSpinBox.setObjectName("syncSpinBox")
        self.horizontalLayout_3.addWidget(self.syncSpinBox)
        self.autoScaleButton = QtWidgets.QPushButton(self.infoWidget)
        self.autoScaleButton.setMinimumSize(QtCore.QSize(75, 0))
        self.autoScaleButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.autoScaleButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.autoScaleButton.setObjectName("autoScaleButton")
        self.horizontalLayout_3.addWidget(self.autoScaleButton)
        self.colorComboBox = QtWidgets.QComboBox(self.infoWidget)
        self.colorComboBox.setMinimumSize(QtCore.QSize(74, 0))
        self.colorComboBox.setMaximumSize(QtCore.QSize(74, 16777215))
        self.colorComboBox.setObjectName("colorComboBox")
        self.horizontalLayout_3.addWidget(self.colorComboBox)
        self.verticalLayout_2.addWidget(self.infoWidget)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.scaleMax.setText(_translate("Frame", "TextLabel"))
        self.scaleMin.setText(_translate("Frame", "TextLabel"))
        self.recordButton.setText(_translate("Frame", "Record"))
        self.shutterButton.setText(_translate("Frame", "Open Shutter"))
        self.intensityPosLabel.setText(_translate("Frame", "(0,0)"))
        self.intensityIntLabel.setText(_translate("Frame", "0"))
        self.syncLabel.setText(_translate("Frame", "Display:"))
        self.autoScaleButton.setText(_translate("Frame", "Autoscale"))

from storm_control.hal4000.qtWidgets.qtCameraGraphicsView import QtCameraGraphicsView
from storm_control.hal4000.qtWidgets.qtRecordButton import QtRecordButton
from storm_control.hal4000.qtWidgets.qtShutterButton import QtShutterButton
