# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dualspotcounter.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(561, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(561, 640))
        Dialog.setMaximumSize(QtCore.QSize(561, 640))
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(480, 610, 75, 24))
        self.okButton.setObjectName("okButton")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 541, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.countsTab = QtWidgets.QWidget()
        self.countsTab.setObjectName("countsTab")
        self.graphFrame = QtWidgets.QFrame(self.countsTab)
        self.graphFrame.setGeometry(QtCore.QRect(60, 30, 471, 251))
        self.graphFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.graphFrame.setObjectName("graphFrame")
        self.countsText1 = QtWidgets.QLabel(self.countsTab)
        self.countsText1.setGeometry(QtCore.QRect(20, 10, 141, 16))
        self.countsText1.setObjectName("countsText1")
        self.countsLabel1 = QtWidgets.QLabel(self.countsTab)
        self.countsLabel1.setGeometry(QtCore.QRect(160, 10, 61, 16))
        self.countsLabel1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.countsLabel1.setObjectName("countsLabel1")
        self.minSpinBox = QtWidgets.QSpinBox(self.countsTab)
        self.minSpinBox.setGeometry(QtCore.QRect(5, 530, 51, 22))
        self.minSpinBox.setMaximum(1000)
        self.minSpinBox.setSingleStep(10)
        self.minSpinBox.setObjectName("minSpinBox")
        self.maxSpinBox = QtWidgets.QSpinBox(self.countsTab)
        self.maxSpinBox.setGeometry(QtCore.QRect(5, 30, 51, 22))
        self.maxSpinBox.setMinimum(10)
        self.maxSpinBox.setMaximum(1000)
        self.maxSpinBox.setSingleStep(10)
        self.maxSpinBox.setProperty("value", 1000)
        self.maxSpinBox.setObjectName("maxSpinBox")
        self.graphFrame2 = QtWidgets.QFrame(self.countsTab)
        self.graphFrame2.setGeometry(QtCore.QRect(60, 310, 471, 251))
        self.graphFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphFrame2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.graphFrame2.setObjectName("graphFrame2")
        self.countsText3 = QtWidgets.QLabel(self.countsTab)
        self.countsText3.setGeometry(QtCore.QRect(20, 290, 141, 16))
        self.countsText3.setObjectName("countsText3")
        self.countsLabel3 = QtWidgets.QLabel(self.countsTab)
        self.countsLabel3.setGeometry(QtCore.QRect(160, 290, 61, 16))
        self.countsLabel3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.countsLabel3.setObjectName("countsLabel3")
        self.tabWidget.addTab(self.countsTab, "")
        self.imageTab = QtWidgets.QWidget()
        self.imageTab.setObjectName("imageTab")
        self.imageFrame = QtWidgets.QFrame(self.imageTab)
        self.imageFrame.setGeometry(QtCore.QRect(10, 40, 516, 516))
        self.imageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imageFrame.setObjectName("imageFrame")
        self.countsText2 = QtWidgets.QLabel(self.imageTab)
        self.countsText2.setGeometry(QtCore.QRect(20, 10, 141, 16))
        self.countsText2.setObjectName("countsText2")
        self.countsLabel2 = QtWidgets.QLabel(self.imageTab)
        self.countsLabel2.setGeometry(QtCore.QRect(160, 10, 61, 16))
        self.countsLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.countsLabel2.setObjectName("countsLabel2")
        self.tabWidget.addTab(self.imageTab, "")
        self.imageTab2 = QtWidgets.QWidget()
        self.imageTab2.setObjectName("imageTab2")
        self.countsLabel4 = QtWidgets.QLabel(self.imageTab2)
        self.countsLabel4.setGeometry(QtCore.QRect(160, 10, 61, 16))
        self.countsLabel4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.countsLabel4.setObjectName("countsLabel4")
        self.imageFrame2 = QtWidgets.QFrame(self.imageTab2)
        self.imageFrame2.setGeometry(QtCore.QRect(10, 40, 516, 516))
        self.imageFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imageFrame2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imageFrame2.setObjectName("imageFrame2")
        self.countsText4 = QtWidgets.QLabel(self.imageTab2)
        self.countsText4.setGeometry(QtCore.QRect(20, 10, 141, 16))
        self.countsText4.setObjectName("countsText4")
        self.tabWidget.addTab(self.imageTab2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "HAL-4000 Spot Counter"))
        self.okButton.setText(_translate("Dialog", "Ok"))
        self.countsText1.setText(_translate("Dialog", "Camera1 Total Localizations:"))
        self.countsLabel1.setText(_translate("Dialog", "TextLabel"))
        self.countsText3.setText(_translate("Dialog", "Camera2 Total Localizations:"))
        self.countsLabel3.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.countsTab), _translate("Dialog", "Counts"))
        self.countsText2.setText(_translate("Dialog", "Camera1 Total Localizations:"))
        self.countsLabel2.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.imageTab), _translate("Dialog", "STORM Image 1"))
        self.countsLabel4.setText(_translate("Dialog", "TextLabel"))
        self.countsText4.setText(_translate("Dialog", "Camera2 Total Localizations:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.imageTab2), _translate("Dialog", "STORM Image 2"))

