# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'galvo.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(466, 184)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(10000, 10000))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.xAxisControlBox = QtWidgets.QGroupBox(Dialog)
        self.xAxisControlBox.setObjectName("xAxisControlBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.xAxisControlBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.xOffsetLabel = QtWidgets.QLabel(self.xAxisControlBox)
        self.xOffsetLabel.setObjectName("xOffsetLabel")
        self.gridLayout_2.addWidget(self.xOffsetLabel, 0, 1, 1, 1)
        self.xAmplitudeSpinBox = QtWidgets.QDoubleSpinBox(self.xAxisControlBox)
        self.xAmplitudeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xAmplitudeSpinBox.setMinimum(0.0)
        self.xAmplitudeSpinBox.setMaximum(10.0)
        self.xAmplitudeSpinBox.setSingleStep(0.01)
        self.xAmplitudeSpinBox.setObjectName("xAmplitudeSpinBox")
        self.gridLayout_2.addWidget(self.xAmplitudeSpinBox, 1, 0, 1, 1)
        self.xAmplitudeLabel = QtWidgets.QLabel(self.xAxisControlBox)
        self.xAmplitudeLabel.setObjectName("xAmplitudeLabel")
        self.gridLayout_2.addWidget(self.xAmplitudeLabel, 1, 1, 1, 1)
        self.xFrequencyLabel = QtWidgets.QLabel(self.xAxisControlBox)
        self.xFrequencyLabel.setObjectName("xFrequencyLabel")
        self.gridLayout_2.addWidget(self.xFrequencyLabel, 2, 1, 1, 1)
        self.xOffsetSpinBox = QtWidgets.QDoubleSpinBox(self.xAxisControlBox)
        self.xOffsetSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xOffsetSpinBox.setMinimum(-10.0)
        self.xOffsetSpinBox.setMaximum(10.0)
        self.xOffsetSpinBox.setSingleStep(0.01)
        self.xOffsetSpinBox.setObjectName("xOffsetSpinBox")
        self.gridLayout_2.addWidget(self.xOffsetSpinBox, 0, 0, 1, 1)
        self.xFrequencySpinBox = QtWidgets.QSpinBox(self.xAxisControlBox)
        self.xFrequencySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xFrequencySpinBox.setMaximum(100000)
        self.xFrequencySpinBox.setObjectName("xFrequencySpinBox")
        self.gridLayout_2.addWidget(self.xFrequencySpinBox, 2, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.xAxisControlBox)
        self.yAxisControlBox = QtWidgets.QGroupBox(Dialog)
        self.yAxisControlBox.setObjectName("yAxisControlBox")
        self.gridLayout = QtWidgets.QGridLayout(self.yAxisControlBox)
        self.gridLayout.setObjectName("gridLayout")
        self.yOffsetSpinBox = QtWidgets.QDoubleSpinBox(self.yAxisControlBox)
        self.yOffsetSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yOffsetSpinBox.setMinimum(-10.0)
        self.yOffsetSpinBox.setMaximum(10.0)
        self.yOffsetSpinBox.setSingleStep(0.01)
        self.yOffsetSpinBox.setObjectName("yOffsetSpinBox")
        self.gridLayout.addWidget(self.yOffsetSpinBox, 0, 0, 1, 1)
        self.yOffsetLabel = QtWidgets.QLabel(self.yAxisControlBox)
        self.yOffsetLabel.setObjectName("yOffsetLabel")
        self.gridLayout.addWidget(self.yOffsetLabel, 0, 1, 1, 1)
        self.yAmplitudeSpinBox = QtWidgets.QDoubleSpinBox(self.yAxisControlBox)
        self.yAmplitudeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yAmplitudeSpinBox.setMinimum(0.0)
        self.yAmplitudeSpinBox.setMaximum(10.0)
        self.yAmplitudeSpinBox.setSingleStep(0.01)
        self.yAmplitudeSpinBox.setObjectName("yAmplitudeSpinBox")
        self.gridLayout.addWidget(self.yAmplitudeSpinBox, 1, 0, 1, 1)
        self.yAmplitudeLabel = QtWidgets.QLabel(self.yAxisControlBox)
        self.yAmplitudeLabel.setObjectName("yAmplitudeLabel")
        self.gridLayout.addWidget(self.yAmplitudeLabel, 1, 1, 1, 1)
        self.yFrequencyLabel = QtWidgets.QLabel(self.yAxisControlBox)
        self.yFrequencyLabel.setObjectName("yFrequencyLabel")
        self.gridLayout.addWidget(self.yFrequencyLabel, 2, 1, 1, 1)
        self.yFrequencySpinBox = QtWidgets.QSpinBox(self.yAxisControlBox)
        self.yFrequencySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yFrequencySpinBox.setMaximum(100000)
        self.yFrequencySpinBox.setObjectName("yFrequencySpinBox")
        self.gridLayout.addWidget(self.yFrequencySpinBox, 2, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.yAxisControlBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.activateButton = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activateButton.sizePolicy().hasHeightForWidth())
        self.activateButton.setSizePolicy(sizePolicy)
        self.activateButton.setCheckable(True)
        self.activateButton.setObjectName("activateButton")
        self.horizontalLayout.addWidget(self.activateButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "HAL-4000 Galvonometer Control"))
        self.xAxisControlBox.setTitle(_translate("Dialog", "X Axis"))
        self.xOffsetLabel.setText(_translate("Dialog", "Offset (V)"))
        self.xAmplitudeLabel.setText(_translate("Dialog", "Amplitude (V)"))
        self.xFrequencyLabel.setText(_translate("Dialog", "Frequency (Hz)"))
        self.yAxisControlBox.setTitle(_translate("Dialog", "Y Axis"))
        self.yOffsetLabel.setText(_translate("Dialog", "Offset (V)"))
        self.yAmplitudeLabel.setText(_translate("Dialog", "Amplitude (V)"))
        self.yFrequencyLabel.setText(_translate("Dialog", "Frequency (Hz)"))
        self.activateButton.setText(_translate("Dialog", "Activate"))
        self.okButton.setText(_translate("Dialog", "Ok"))

