# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'galvo.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(360, 180))
        Dialog.setMaximumSize(QtCore.QSize(360, 180))
        self.focusLockBox = QtWidgets.QGroupBox(Dialog)
        self.focusLockBox.setGeometry(QtCore.QRect(10, 0, 341, 141))
        self.focusLockBox.setObjectName("focusLockBox")
        self.xAxisControlBox = QtWidgets.QGroupBox(self.focusLockBox)
        self.xAxisControlBox.setGeometry(QtCore.QRect(10, 20, 155, 105))
        self.xAxisControlBox.setObjectName("xAxisControlBox")
        self.gridLayout = QtWidgets.QGridLayout(self.xAxisControlBox)
        self.gridLayout.setObjectName("gridLayout")
        self.xOffsetSpinBox = QtWidgets.QDoubleSpinBox(self.xAxisControlBox)
        self.xOffsetSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xOffsetSpinBox.setMinimum(-10.0)
        self.xOffsetSpinBox.setMaximum(10.0)
        self.xOffsetSpinBox.setSingleStep(0.01)
        self.xOffsetSpinBox.setObjectName("xOffsetSpinBox")
        self.gridLayout.addWidget(self.xOffsetSpinBox, 0, 0, 1, 1)
        self.xOffsetLabel = QtWidgets.QLabel(self.xAxisControlBox)
        self.xOffsetLabel.setObjectName("xOffsetLabel")
        self.gridLayout.addWidget(self.xOffsetLabel, 0, 1, 1, 1)
        self.xAmplitudeSpinBox = QtWidgets.QDoubleSpinBox(self.xAxisControlBox)
        self.xAmplitudeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xAmplitudeSpinBox.setMinimum(0.0)
        self.xAmplitudeSpinBox.setMaximum(10.0)
        self.xAmplitudeSpinBox.setSingleStep(0.01)
        self.xAmplitudeSpinBox.setObjectName("xAmplitudeSpinBox")
        self.gridLayout.addWidget(self.xAmplitudeSpinBox, 1, 0, 1, 1)
        self.xAmplitudeLabel = QtWidgets.QLabel(self.xAxisControlBox)
        self.xAmplitudeLabel.setObjectName("xAmplitudeLabel")
        self.gridLayout.addWidget(self.xAmplitudeLabel, 1, 1, 1, 1)
        self.xFrequencySpinBox = QtWidgets.QDoubleSpinBox(self.xAxisControlBox)
        self.xFrequencySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xFrequencySpinBox.setMinimum(0.0)
        self.xFrequencySpinBox.setMaximum(2500.0)
        self.xFrequencySpinBox.setSingleStep(0.01)
        self.xFrequencySpinBox.setObjectName("xFrequencySpinBox")
        self.gridLayout.addWidget(self.xFrequencySpinBox, 2, 0, 1, 1)
        self.xFrequencyLabel = QtWidgets.QLabel(self.xAxisControlBox)
        self.xFrequencyLabel.setObjectName("xFrequencyLabel")
        self.gridLayout.addWidget(self.xFrequencyLabel, 2, 1, 1, 1)
        self.yAxisControlBox = QtWidgets.QGroupBox(self.focusLockBox)
        self.yAxisControlBox.setGeometry(QtCore.QRect(170, 20, 155, 105))
        self.yAxisControlBox.setObjectName("yAxisControlBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.yAxisControlBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.yOffsetSpinBox = QtWidgets.QDoubleSpinBox(self.yAxisControlBox)
        self.yOffsetSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yOffsetSpinBox.setMinimum(-10.0)
        self.yOffsetSpinBox.setMaximum(10.0)
        self.yOffsetSpinBox.setSingleStep(0.01)
        self.yOffsetSpinBox.setObjectName("yOffsetSpinBox")
        self.gridLayout_2.addWidget(self.yOffsetSpinBox, 0, 0, 1, 1)
        self.yOffsetLabel = QtWidgets.QLabel(self.yAxisControlBox)
        self.yOffsetLabel.setObjectName("yOffsetLabel")
        self.gridLayout_2.addWidget(self.yOffsetLabel, 0, 1, 1, 1)
        self.yAmplitudeSpinBox = QtWidgets.QDoubleSpinBox(self.yAxisControlBox)
        self.yAmplitudeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yAmplitudeSpinBox.setMinimum(0.0)
        self.yAmplitudeSpinBox.setMaximum(10.0)
        self.yAmplitudeSpinBox.setSingleStep(0.01)
        self.yAmplitudeSpinBox.setObjectName("yAmplitudeSpinBox")
        self.gridLayout_2.addWidget(self.yAmplitudeSpinBox, 1, 0, 1, 1)
        self.yAmplitudeLabel = QtWidgets.QLabel(self.yAxisControlBox)
        self.yAmplitudeLabel.setObjectName("yAmplitudeLabel")
        self.gridLayout_2.addWidget(self.yAmplitudeLabel, 1, 1, 1, 1)
        self.yFrequencySpinBox = QtWidgets.QDoubleSpinBox(self.yAxisControlBox)
        self.yFrequencySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yFrequencySpinBox.setMinimum(0.0)
        self.yFrequencySpinBox.setMaximum(2500.0)
        self.yFrequencySpinBox.setSingleStep(0.01)
        self.yFrequencySpinBox.setObjectName("yFrequencySpinBox")
        self.gridLayout_2.addWidget(self.yFrequencySpinBox, 2, 0, 1, 1)
        self.yFrequencyLabel = QtWidgets.QLabel(self.yAxisControlBox)
        self.yFrequencyLabel.setObjectName("yFrequencyLabel")
        self.gridLayout_2.addWidget(self.yFrequencyLabel, 2, 1, 1, 1)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(280, 150, 75, 24))
        self.okButton.setObjectName("okButton")
        self.activateButton = QtWidgets.QPushButton(Dialog)
        self.activateButton.setGeometry(QtCore.QRect(10, 150, 75, 24))
        self.activateButton.setObjectName("activateButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "HAL-4000 Galvonometer Control"))
        self.focusLockBox.setTitle(_translate("Dialog", "Galvonometer Control"))
        self.xAxisControlBox.setTitle(_translate("Dialog", "X Axis"))
        self.xOffsetLabel.setText(_translate("Dialog", "Offset (V)"))
        self.xAmplitudeLabel.setText(_translate("Dialog", "Amplitude (V)"))
        self.xFrequencyLabel.setText(_translate("Dialog", "Frequency (Hz)"))
        self.yAxisControlBox.setTitle(_translate("Dialog", "Y Axis"))
        self.yOffsetLabel.setText(_translate("Dialog", "Offset (V)"))
        self.yAmplitudeLabel.setText(_translate("Dialog", "Amplitude (V)"))
        self.yFrequencyLabel.setText(_translate("Dialog", "Frequency (Hz)"))
        self.okButton.setText(_translate("Dialog", "Ok"))
        self.activateButton.setText(_translate("Dialog", "Activate"))

