# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lockdisplay.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(298, 249)
        self.statusBox = QtWidgets.QGroupBox(Form)
        self.statusBox.setGeometry(QtCore.QRect(10, 0, 281, 241))
        self.statusBox.setObjectName("statusBox")
        self.offsetFrame = QtWidgets.QFrame(self.statusBox)
        self.offsetFrame.setGeometry(QtCore.QRect(20, 40, 21, 161))
        self.offsetFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.offsetFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.offsetFrame.setObjectName("offsetFrame")
        self.offsetLabel = QtWidgets.QLabel(self.statusBox)
        self.offsetLabel.setGeometry(QtCore.QRect(8, 20, 46, 14))
        self.offsetLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.offsetLabel.setObjectName("offsetLabel")
        self.zFrame = QtWidgets.QFrame(self.statusBox)
        self.zFrame.setGeometry(QtCore.QRect(111, 40, 21, 161))
        self.zFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.zFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.zFrame.setObjectName("zFrame")
        self.zLabel = QtWidgets.QLabel(self.statusBox)
        self.zLabel.setGeometry(QtCore.QRect(97, 20, 46, 14))
        self.zLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zLabel.setObjectName("zLabel")
        self.sumLabel = QtWidgets.QLabel(self.statusBox)
        self.sumLabel.setGeometry(QtCore.QRect(52, 20, 46, 14))
        self.sumLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sumLabel.setObjectName("sumLabel")
        self.sumFrame = QtWidgets.QFrame(self.statusBox)
        self.sumFrame.setGeometry(QtCore.QRect(65, 40, 21, 161))
        self.sumFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sumFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.sumFrame.setObjectName("sumFrame")
        self.offsetText = QtWidgets.QLabel(self.statusBox)
        self.offsetText.setGeometry(QtCore.QRect(10, 210, 46, 14))
        self.offsetText.setAlignment(QtCore.Qt.AlignCenter)
        self.offsetText.setObjectName("offsetText")
        self.sumText = QtWidgets.QLabel(self.statusBox)
        self.sumText.setGeometry(QtCore.QRect(54, 210, 46, 14))
        self.sumText.setAlignment(QtCore.Qt.AlignCenter)
        self.sumText.setObjectName("sumText")
        self.zText = QtWidgets.QLabel(self.statusBox)
        self.zText.setGeometry(QtCore.QRect(92, 209, 61, 16))
        self.zText.setAlignment(QtCore.Qt.AlignCenter)
        self.zText.setObjectName("zText")
        self.qpdFrame = QtWidgets.QFrame(self.statusBox)
        self.qpdFrame.setGeometry(QtCore.QRect(146, 40, 120, 120))
        self.qpdFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.qpdFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.qpdFrame.setObjectName("qpdFrame")
        self.qpdLabel = QtWidgets.QLabel(self.statusBox)
        self.qpdLabel.setGeometry(QtCore.QRect(170, 20, 71, 16))
        self.qpdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.qpdLabel.setObjectName("qpdLabel")
        self.qpdXText = QtWidgets.QLabel(self.statusBox)
        self.qpdXText.setGeometry(QtCore.QRect(153, 168, 46, 14))
        self.qpdXText.setObjectName("qpdXText")
        self.qpdYText = QtWidgets.QLabel(self.statusBox)
        self.qpdYText.setGeometry(QtCore.QRect(213, 168, 46, 14))
        self.qpdYText.setObjectName("qpdYText")
        self.irButton = QtWidgets.QPushButton(self.statusBox)
        self.irButton.setGeometry(QtCore.QRect(211, 210, 61, 24))
        self.irButton.setObjectName("irButton")
        self.irSlider = QtWidgets.QSlider(self.statusBox)
        self.irSlider.setGeometry(QtCore.QRect(155, 189, 101, 19))
        self.irSlider.setMinimum(0)
        self.irSlider.setMaximum(100)
        self.irSlider.setProperty("value", 0)
        self.irSlider.setOrientation(QtCore.Qt.Horizontal)
        self.irSlider.setObjectName("irSlider")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.statusBox.setTitle(_translate("Form", "Status"))
        self.offsetLabel.setText(_translate("Form", "Offset"))
        self.zLabel.setText(_translate("Form", "Stage Z"))
        self.sumLabel.setText(_translate("Form", "Sum"))
        self.offsetText.setText(_translate("Form", "TextLabel"))
        self.sumText.setText(_translate("Form", "TextLabel"))
        self.zText.setText(_translate("Form", "TextLabel"))
        self.qpdLabel.setText(_translate("Form", "QPD Signal"))
        self.qpdXText.setText(_translate("Form", "x:"))
        self.qpdYText.setText(_translate("Form", "y:"))
        self.irButton.setText(_translate("Form", "IR ON"))

