# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progression.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(325, 265)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(10000, 10000))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressionsBox = QtWidgets.QGroupBox(Dialog)
        self.progressionsBox.setObjectName("progressionsBox")
        self.gridLayout = QtWidgets.QGridLayout(self.progressionsBox)
        self.gridLayout.setContentsMargins(0, -1, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.progressionsBox)
        self.tabWidget.setObjectName("tabWidget")
        self.linearTab = QtWidgets.QWidget()
        self.linearTab.setObjectName("linearTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.linearTab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.channelLabel = QtWidgets.QLabel(self.linearTab)
        self.channelLabel.setObjectName("channelLabel")
        self.gridLayout_2.addWidget(self.channelLabel, 0, 0, 1, 1)
        self.activeLabel = QtWidgets.QLabel(self.linearTab)
        self.activeLabel.setObjectName("activeLabel")
        self.gridLayout_2.addWidget(self.activeLabel, 0, 1, 1, 1)
        self.startLabel = QtWidgets.QLabel(self.linearTab)
        self.startLabel.setObjectName("startLabel")
        self.gridLayout_2.addWidget(self.startLabel, 0, 2, 1, 1)
        self.incrementLabel = QtWidgets.QLabel(self.linearTab)
        self.incrementLabel.setObjectName("incrementLabel")
        self.gridLayout_2.addWidget(self.incrementLabel, 0, 3, 1, 1)
        self.framesLabel = QtWidgets.QLabel(self.linearTab)
        self.framesLabel.setObjectName("framesLabel")
        self.gridLayout_2.addWidget(self.framesLabel, 0, 4, 1, 1)
        self.tabWidget.addTab(self.linearTab, "")
        self.expTab = QtWidgets.QWidget()
        self.expTab.setObjectName("expTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.expTab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.channelLabel_2 = QtWidgets.QLabel(self.expTab)
        self.channelLabel_2.setObjectName("channelLabel_2")
        self.gridLayout_3.addWidget(self.channelLabel_2, 0, 0, 1, 1)
        self.activeLabel_2 = QtWidgets.QLabel(self.expTab)
        self.activeLabel_2.setObjectName("activeLabel_2")
        self.gridLayout_3.addWidget(self.activeLabel_2, 0, 1, 1, 1)
        self.startLabel_2 = QtWidgets.QLabel(self.expTab)
        self.startLabel_2.setObjectName("startLabel_2")
        self.gridLayout_3.addWidget(self.startLabel_2, 0, 2, 1, 1)
        self.incrementLabel_2 = QtWidgets.QLabel(self.expTab)
        self.incrementLabel_2.setObjectName("incrementLabel_2")
        self.gridLayout_3.addWidget(self.incrementLabel_2, 0, 3, 1, 1)
        self.framesLabel_2 = QtWidgets.QLabel(self.expTab)
        self.framesLabel_2.setObjectName("framesLabel_2")
        self.gridLayout_3.addWidget(self.framesLabel_2, 0, 4, 1, 1)
        self.tabWidget.addTab(self.expTab, "")
        self.fileTab = QtWidgets.QWidget()
        self.fileTab.setObjectName("fileTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fileTab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.powerLabel = QtWidgets.QLabel(self.fileTab)
        self.powerLabel.setObjectName("powerLabel")
        self.verticalLayout_2.addWidget(self.powerLabel)
        self.filenameLabel = QtWidgets.QLabel(self.fileTab)
        self.filenameLabel.setObjectName("filenameLabel")
        self.verticalLayout_2.addWidget(self.filenameLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.loadFileButton = QtWidgets.QPushButton(self.fileTab)
        self.loadFileButton.setObjectName("loadFileButton")
        self.horizontalLayout_2.addWidget(self.loadFileButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.powerLabel.raise_()
        self.loadFileButton.raise_()
        self.filenameLabel.raise_()
        self.loadFileButton.raise_()
        self.tabWidget.addTab(self.fileTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.progressionsBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressionsCheckBox = QtWidgets.QCheckBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressionsCheckBox.sizePolicy().hasHeightForWidth())
        self.progressionsCheckBox.setSizePolicy(sizePolicy)
        self.progressionsCheckBox.setObjectName("progressionsCheckBox")
        self.horizontalLayout.addWidget(self.progressionsCheckBox)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "HAL-4000 Power Progressions"))
        self.progressionsBox.setTitle(_translate("Dialog", "Power Progressions"))
        self.channelLabel.setText(_translate("Dialog", "Channel"))
        self.activeLabel.setText(_translate("Dialog", "Active"))
        self.startLabel.setText(_translate("Dialog", "Start"))
        self.incrementLabel.setText(_translate("Dialog", "Increment"))
        self.framesLabel.setText(_translate("Dialog", "Frames"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.linearTab), _translate("Dialog", "Linear"))
        self.channelLabel_2.setText(_translate("Dialog", "Channel"))
        self.activeLabel_2.setText(_translate("Dialog", "Active"))
        self.startLabel_2.setText(_translate("Dialog", "Start"))
        self.incrementLabel_2.setText(_translate("Dialog", "Multiplier"))
        self.framesLabel_2.setText(_translate("Dialog", "Frames"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.expTab), _translate("Dialog", "Exponential"))
        self.powerLabel.setText(_translate("Dialog", "Power File:"))
        self.filenameLabel.setText(_translate("Dialog", "None"))
        self.loadFileButton.setText(_translate("Dialog", "Load File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fileTab), _translate("Dialog", "From File"))
        self.progressionsCheckBox.setText(_translate("Dialog", "Use Power Progressions"))
        self.okButton.setText(_translate("Dialog", "Ok"))

