# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stage.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(508, 354)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(10000, 10000))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.saveGroupBox = QtWidgets.QGroupBox(Dialog)
        self.saveGroupBox.setMinimumSize(QtCore.QSize(205, 120))
        self.saveGroupBox.setObjectName("saveGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.saveGroupBox)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.saveComboBox = QtWidgets.QComboBox(self.saveGroupBox)
        self.saveComboBox.setObjectName("saveComboBox")
        self.verticalLayout.addWidget(self.saveComboBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(self.saveGroupBox)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.clearButton = QtWidgets.QPushButton(self.saveGroupBox)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveButton = QtWidgets.QPushButton(self.saveGroupBox)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.loadButton = QtWidgets.QPushButton(self.saveGroupBox)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_2.addWidget(self.loadButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.saveGroupBox, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.upLButton = QtWidgets.QPushButton(Dialog)
        self.upLButton.setMinimumSize(QtCore.QSize(66, 68))
        self.upLButton.setMaximumSize(QtCore.QSize(66, 68))
        self.upLButton.setText("")
        self.upLButton.setIconSize(QtCore.QSize(56, 56))
        self.upLButton.setObjectName("upLButton")
        self.verticalLayout_5.addWidget(self.upLButton)
        self.upSButton = QtWidgets.QPushButton(Dialog)
        self.upSButton.setMinimumSize(QtCore.QSize(66, 52))
        self.upSButton.setMaximumSize(QtCore.QSize(66, 52))
        self.upSButton.setText("")
        self.upSButton.setIconSize(QtCore.QSize(56, 56))
        self.upSButton.setObjectName("upSButton")
        self.verticalLayout_5.addWidget(self.upSButton)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.posGroupBox = QtWidgets.QGroupBox(Dialog)
        self.posGroupBox.setMinimumSize(QtCore.QSize(205, 120))
        self.posGroupBox.setObjectName("posGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.posGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.xposLabel = QtWidgets.QLabel(self.posGroupBox)
        self.xposLabel.setObjectName("xposLabel")
        self.horizontalLayout_3.addWidget(self.xposLabel)
        self.xposText = QtWidgets.QLabel(self.posGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xposText.sizePolicy().hasHeightForWidth())
        self.xposText.setSizePolicy(sizePolicy)
        self.xposText.setText("")
        self.xposText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xposText.setObjectName("xposText")
        self.horizontalLayout_3.addWidget(self.xposText)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.yposLabel = QtWidgets.QLabel(self.posGroupBox)
        self.yposLabel.setObjectName("yposLabel")
        self.horizontalLayout_4.addWidget(self.yposLabel)
        self.yposText = QtWidgets.QLabel(self.posGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yposText.sizePolicy().hasHeightForWidth())
        self.yposText.setSizePolicy(sizePolicy)
        self.yposText.setText("")
        self.yposText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yposText.setObjectName("yposText")
        self.horizontalLayout_4.addWidget(self.yposText)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.zeroButton = QtWidgets.QPushButton(self.posGroupBox)
        self.zeroButton.setObjectName("zeroButton")
        self.horizontalLayout_5.addWidget(self.zeroButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout.addWidget(self.posGroupBox, 0, 2, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.leftLButton = QtWidgets.QPushButton(Dialog)
        self.leftLButton.setMinimumSize(QtCore.QSize(68, 66))
        self.leftLButton.setText("")
        self.leftLButton.setIconSize(QtCore.QSize(56, 56))
        self.leftLButton.setObjectName("leftLButton")
        self.horizontalLayout_6.addWidget(self.leftLButton)
        self.leftSButton = QtWidgets.QPushButton(Dialog)
        self.leftSButton.setMinimumSize(QtCore.QSize(52, 66))
        self.leftSButton.setMaximumSize(QtCore.QSize(52, 66))
        self.leftSButton.setText("")
        self.leftSButton.setIconSize(QtCore.QSize(56, 56))
        self.leftSButton.setObjectName("leftSButton")
        self.horizontalLayout_6.addWidget(self.leftSButton)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.homeButton = QtWidgets.QPushButton(Dialog)
        self.homeButton.setMinimumSize(QtCore.QSize(51, 51))
        self.homeButton.setMaximumSize(QtCore.QSize(51, 51))
        self.homeButton.setObjectName("homeButton")
        self.gridLayout.addWidget(self.homeButton, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.rightSButton = QtWidgets.QPushButton(Dialog)
        self.rightSButton.setMinimumSize(QtCore.QSize(52, 66))
        self.rightSButton.setMaximumSize(QtCore.QSize(52, 66))
        self.rightSButton.setText("")
        self.rightSButton.setIconSize(QtCore.QSize(56, 56))
        self.rightSButton.setObjectName("rightSButton")
        self.horizontalLayout_11.addWidget(self.rightSButton)
        self.rightLButton = QtWidgets.QPushButton(Dialog)
        self.rightLButton.setMinimumSize(QtCore.QSize(68, 66))
        self.rightLButton.setMaximumSize(QtCore.QSize(68, 66))
        self.rightLButton.setText("")
        self.rightLButton.setIconSize(QtCore.QSize(56, 56))
        self.rightLButton.setObjectName("rightLButton")
        self.horizontalLayout_11.addWidget(self.rightLButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_11, 1, 2, 1, 1)
        self.moveGroupBox = QtWidgets.QGroupBox(Dialog)
        self.moveGroupBox.setMinimumSize(QtCore.QSize(205, 120))
        self.moveGroupBox.setObjectName("moveGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.moveGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.xmoveLabel = QtWidgets.QLabel(self.moveGroupBox)
        self.xmoveLabel.setObjectName("xmoveLabel")
        self.horizontalLayout_7.addWidget(self.xmoveLabel)
        self.xmoveDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.moveGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xmoveDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.xmoveDoubleSpinBox.setSizePolicy(sizePolicy)
        self.xmoveDoubleSpinBox.setDecimals(1)
        self.xmoveDoubleSpinBox.setMinimum(-100000.0)
        self.xmoveDoubleSpinBox.setMaximum(100000.0)
        self.xmoveDoubleSpinBox.setObjectName("xmoveDoubleSpinBox")
        self.horizontalLayout_7.addWidget(self.xmoveDoubleSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ymoveLabel = QtWidgets.QLabel(self.moveGroupBox)
        self.ymoveLabel.setObjectName("ymoveLabel")
        self.horizontalLayout_8.addWidget(self.ymoveLabel)
        self.ymoveDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.moveGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ymoveDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.ymoveDoubleSpinBox.setSizePolicy(sizePolicy)
        self.ymoveDoubleSpinBox.setDecimals(1)
        self.ymoveDoubleSpinBox.setMinimum(-100000.0)
        self.ymoveDoubleSpinBox.setMaximum(100000.0)
        self.ymoveDoubleSpinBox.setObjectName("ymoveDoubleSpinBox")
        self.horizontalLayout_8.addWidget(self.ymoveDoubleSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.goButton = QtWidgets.QPushButton(self.moveGroupBox)
        self.goButton.setObjectName("goButton")
        self.horizontalLayout_9.addWidget(self.goButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.gridLayout.addWidget(self.moveGroupBox, 2, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.downSButton = QtWidgets.QPushButton(Dialog)
        self.downSButton.setMinimumSize(QtCore.QSize(66, 52))
        self.downSButton.setMaximumSize(QtCore.QSize(66, 52))
        self.downSButton.setText("")
        self.downSButton.setIconSize(QtCore.QSize(56, 56))
        self.downSButton.setObjectName("downSButton")
        self.verticalLayout_8.addWidget(self.downSButton)
        self.downLButton = QtWidgets.QPushButton(Dialog)
        self.downLButton.setMinimumSize(QtCore.QSize(66, 68))
        self.downLButton.setMaximumSize(QtCore.QSize(66, 68))
        self.downLButton.setText("")
        self.downLButton.setIconSize(QtCore.QSize(56, 56))
        self.downLButton.setObjectName("downLButton")
        self.verticalLayout_8.addWidget(self.downLButton)
        self.gridLayout.addLayout(self.verticalLayout_8, 2, 1, 1, 1)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(20, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.okButton = QtWidgets.QPushButton(self.widget)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_10.addWidget(self.okButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.gridLayout.addWidget(self.widget, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "HAL-4000 Stage Control"))
        self.saveGroupBox.setTitle(_translate("Dialog", "Saved Positions"))
        self.addButton.setText(_translate("Dialog", "Add"))
        self.clearButton.setText(_translate("Dialog", "Clear"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.loadButton.setText(_translate("Dialog", "Load"))
        self.posGroupBox.setTitle(_translate("Dialog", "Current Position"))
        self.xposLabel.setText(_translate("Dialog", "X (um):"))
        self.yposLabel.setText(_translate("Dialog", "Y (um):"))
        self.zeroButton.setText(_translate("Dialog", "Zero"))
        self.homeButton.setText(_translate("Dialog", "Home"))
        self.moveGroupBox.setTitle(_translate("Dialog", "Move To"))
        self.xmoveLabel.setText(_translate("Dialog", "X (um):"))
        self.ymoveLabel.setText(_translate("Dialog", "Y (um):"))
        self.goButton.setText(_translate("Dialog", "Go"))
        self.okButton.setText(_translate("Dialog", "Ok"))

