# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'storm3-misc.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(322, 392)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(322, 392))
        Dialog.setMaximumSize(QtCore.QSize(322, 392))
        self.TIRFgroupBox = QtWidgets.QGroupBox(Dialog)
        self.TIRFgroupBox.setGeometry(QtCore.QRect(9, 9, 304, 111))
        self.TIRFgroupBox.setObjectName("TIRFgroupBox")
        self.leftLargeButton = QtWidgets.QPushButton(self.TIRFgroupBox)
        self.leftLargeButton.setGeometry(QtCore.QRect(53, 20, 31, 24))
        self.leftLargeButton.setObjectName("leftLargeButton")
        self.rightSmallButton = QtWidgets.QPushButton(self.TIRFgroupBox)
        self.rightSmallButton.setGeometry(QtCore.QRect(106, 20, 21, 24))
        self.rightSmallButton.setObjectName("rightSmallButton")
        self.positionLabel = QtWidgets.QLabel(self.TIRFgroupBox)
        self.positionLabel.setGeometry(QtCore.QRect(210, 20, 81, 16))
        self.positionLabel.setObjectName("positionLabel")
        self.positionText = QtWidgets.QLabel(self.TIRFgroupBox)
        self.positionText.setGeometry(QtCore.QRect(230, 40, 46, 14))
        self.positionText.setText("")
        self.positionText.setObjectName("positionText")
        self.EPIButton = QtWidgets.QPushButton(self.TIRFgroupBox)
        self.EPIButton.setGeometry(QtCore.QRect(10, 20, 41, 24))
        self.EPIButton.setObjectName("EPIButton")
        self.TIRFButton = QtWidgets.QPushButton(self.TIRFgroupBox)
        self.TIRFButton.setGeometry(QtCore.QRect(160, 20, 41, 24))
        self.TIRFButton.setObjectName("TIRFButton")
        self.rightLargeButton = QtWidgets.QPushButton(self.TIRFgroupBox)
        self.rightLargeButton.setGeometry(QtCore.QRect(128, 20, 31, 24))
        self.rightLargeButton.setObjectName("rightLargeButton")
        self.leftSmallButton = QtWidgets.QPushButton(self.TIRFgroupBox)
        self.leftSmallButton.setGeometry(QtCore.QRect(85, 20, 20, 24))
        self.leftSmallButton.setObjectName("leftSmallButton")
        self.moveGroupBox = QtWidgets.QGroupBox(self.TIRFgroupBox)
        self.moveGroupBox.setGeometry(QtCore.QRect(10, 50, 191, 51))
        self.moveGroupBox.setObjectName("moveGroupBox")
        self.tirSpinBox = QtWidgets.QDoubleSpinBox(self.moveGroupBox)
        self.tirSpinBox.setGeometry(QtCore.QRect(10, 20, 71, 22))
        self.tirSpinBox.setDecimals(3)
        self.tirSpinBox.setMaximum(25.0)
        self.tirSpinBox.setSingleStep(0.001)
        self.tirSpinBox.setProperty("value", 21.0)
        self.tirSpinBox.setObjectName("tirSpinBox")
        self.tirGoButton = QtWidgets.QPushButton(self.moveGroupBox)
        self.tirGoButton.setGeometry(QtCore.QRect(98, 19, 75, 24))
        self.tirGoButton.setObjectName("tirGoButton")
        self.dYAGGroupBox = QtWidgets.QGroupBox(Dialog)
        self.dYAGGroupBox.setGeometry(QtCore.QRect(9, 126, 304, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dYAGGroupBox.sizePolicy().hasHeightForWidth())
        self.dYAGGroupBox.setSizePolicy(sizePolicy)
        self.dYAGGroupBox.setObjectName("dYAGGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dYAGGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filter1Button = QtWidgets.QPushButton(self.dYAGGroupBox)
        self.filter1Button.setCheckable(True)
        self.filter1Button.setAutoExclusive(True)
        self.filter1Button.setObjectName("filter1Button")
        self.horizontalLayout.addWidget(self.filter1Button)
        self.filter2Button = QtWidgets.QPushButton(self.dYAGGroupBox)
        self.filter2Button.setCheckable(True)
        self.filter2Button.setAutoExclusive(True)
        self.filter2Button.setObjectName("filter2Button")
        self.horizontalLayout.addWidget(self.filter2Button)
        self.filter3Button = QtWidgets.QPushButton(self.dYAGGroupBox)
        self.filter3Button.setCheckable(True)
        self.filter3Button.setAutoExclusive(True)
        self.filter3Button.setObjectName("filter3Button")
        self.horizontalLayout.addWidget(self.filter3Button)
        self.filter4Button = QtWidgets.QPushButton(self.dYAGGroupBox)
        self.filter4Button.setCheckable(True)
        self.filter4Button.setAutoExclusive(True)
        self.filter4Button.setObjectName("filter4Button")
        self.horizontalLayout.addWidget(self.filter4Button)
        self.filter5Button = QtWidgets.QPushButton(self.dYAGGroupBox)
        self.filter5Button.setCheckable(True)
        self.filter5Button.setAutoExclusive(True)
        self.filter5Button.setObjectName("filter5Button")
        self.horizontalLayout.addWidget(self.filter5Button)
        self.filter6Button = QtWidgets.QPushButton(self.dYAGGroupBox)
        self.filter6Button.setCheckable(True)
        self.filter6Button.setAutoExclusive(True)
        self.filter6Button.setObjectName("filter6Button")
        self.horizontalLayout.addWidget(self.filter6Button)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(237, 359, 77, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setObjectName("okButton")
        self.iEyesGroupBox = QtWidgets.QGroupBox(Dialog)
        self.iEyesGroupBox.setGeometry(QtCore.QRect(10, 190, 304, 161))
        self.iEyesGroupBox.setObjectName("iEyesGroupBox")
        self.iEyesSaveButton = QtWidgets.QPushButton(self.iEyesGroupBox)
        self.iEyesSaveButton.setGeometry(QtCore.QRect(10, 45, 77, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iEyesSaveButton.sizePolicy().hasHeightForWidth())
        self.iEyesSaveButton.setSizePolicy(sizePolicy)
        self.iEyesSaveButton.setObjectName("iEyesSaveButton")
        self.iEyesLabel = QtWidgets.QLabel(self.iEyesGroupBox)
        self.iEyesLabel.setGeometry(QtCore.QRect(150, 22, 141, 16))
        self.iEyesLabel.setObjectName("iEyesLabel")
        self.iEyesAutoSaveButton = QtWidgets.QPushButton(self.iEyesGroupBox)
        self.iEyesAutoSaveButton.setGeometry(QtCore.QRect(90, 45, 77, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iEyesAutoSaveButton.sizePolicy().hasHeightForWidth())
        self.iEyesAutoSaveButton.setSizePolicy(sizePolicy)
        self.iEyesAutoSaveButton.setObjectName("iEyesAutoSaveButton")
        self.iEyesResetButton = QtWidgets.QPushButton(self.iEyesGroupBox)
        self.iEyesResetButton.setGeometry(QtCore.QRect(220, 45, 77, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iEyesResetButton.sizePolicy().hasHeightForWidth())
        self.iEyesResetButton.setSizePolicy(sizePolicy)
        self.iEyesResetButton.setObjectName("iEyesResetButton")
        self.iEyesROILabel = QtWidgets.QLabel(self.iEyesGroupBox)
        self.iEyesROILabel.setGeometry(QtCore.QRect(12, 74, 281, 20))
        self.iEyesROILabel.setObjectName("iEyesROILabel")
        self.iEyesBackgroundSpinBox = QtWidgets.QSpinBox(self.iEyesGroupBox)
        self.iEyesBackgroundSpinBox.setGeometry(QtCore.QRect(90, 131, 61, 22))
        self.iEyesBackgroundSpinBox.setMaximum(10000)
        self.iEyesBackgroundSpinBox.setSingleStep(1)
        self.iEyesBackgroundSpinBox.setObjectName("iEyesBackgroundSpinBox")
        self.iEyesBackgroundLabel = QtWidgets.QLabel(self.iEyesGroupBox)
        self.iEyesBackgroundLabel.setGeometry(QtCore.QRect(10, 133, 71, 16))
        self.iEyesBackgroundLabel.setObjectName("iEyesBackgroundLabel")
        self.iEyesAccumulateLabel = QtWidgets.QLabel(self.iEyesGroupBox)
        self.iEyesAccumulateLabel.setGeometry(QtCore.QRect(159, 133, 81, 16))
        self.iEyesAccumulateLabel.setObjectName("iEyesAccumulateLabel")
        self.iEyesAccumulateSpinBox = QtWidgets.QSpinBox(self.iEyesGroupBox)
        self.iEyesAccumulateSpinBox.setGeometry(QtCore.QRect(234, 131, 61, 22))
        self.iEyesAccumulateSpinBox.setMinimum(1)
        self.iEyesAccumulateSpinBox.setObjectName("iEyesAccumulateSpinBox")
        self.iEyesLineEdit = QtWidgets.QLineEdit(self.iEyesGroupBox)
        self.iEyesLineEdit.setGeometry(QtCore.QRect(10, 20, 111, 20))
        self.iEyesLineEdit.setObjectName("iEyesLineEdit")
        self.iEyesClearROIButton = QtWidgets.QPushButton(self.iEyesGroupBox)
        self.iEyesClearROIButton.setGeometry(QtCore.QRect(10, 99, 77, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iEyesClearROIButton.sizePolicy().hasHeightForWidth())
        self.iEyesClearROIButton.setSizePolicy(sizePolicy)
        self.iEyesClearROIButton.setObjectName("iEyesClearROIButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "HAL-4000 Miscellaneous Controls"))
        self.TIRFgroupBox.setTitle(_translate("Dialog", "TIRF Control"))
        self.leftLargeButton.setText(_translate("Dialog", "<<"))
        self.rightSmallButton.setText(_translate("Dialog", ">"))
        self.positionLabel.setText(_translate("Dialog", "Current Postion:"))
        self.EPIButton.setText(_translate("Dialog", "EPI"))
        self.TIRFButton.setText(_translate("Dialog", "TIRF"))
        self.rightLargeButton.setText(_translate("Dialog", ">>"))
        self.leftSmallButton.setText(_translate("Dialog", "<"))
        self.moveGroupBox.setTitle(_translate("Dialog", "Move To"))
        self.tirGoButton.setText(_translate("Dialog", "Go"))
        self.dYAGGroupBox.setTitle(_translate("Dialog", "Filter Wheel"))
        self.filter1Button.setText(_translate("Dialog", "1"))
        self.filter2Button.setText(_translate("Dialog", "2"))
        self.filter3Button.setText(_translate("Dialog", "3"))
        self.filter4Button.setText(_translate("Dialog", "4"))
        self.filter5Button.setText(_translate("Dialog", "5"))
        self.filter6Button.setText(_translate("Dialog", "6"))
        self.okButton.setText(_translate("Dialog", "Ok"))
        self.iEyesGroupBox.setTitle(_translate("Dialog", "Imagine Eyes"))
        self.iEyesSaveButton.setText(_translate("Dialog", "Save Frame"))
        self.iEyesLabel.setText(_translate("Dialog", "filename"))
        self.iEyesAutoSaveButton.setText(_translate("Dialog", "Auto Save"))
        self.iEyesResetButton.setText(_translate("Dialog", "Reset"))
        self.iEyesROILabel.setText(_translate("Dialog", "TextLabel"))
        self.iEyesBackgroundLabel.setText(_translate("Dialog", "Background:"))
        self.iEyesAccumulateLabel.setText(_translate("Dialog", "Accumulate:"))
        self.iEyesLineEdit.setText(_translate("Dialog", "img.ch00"))
        self.iEyesClearROIButton.setText(_translate("Dialog", "Reset ROI"))

