# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'steve.ui'
#
# Created: Tue Feb 25 10:27:03 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(937, 727)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.mosaicTab = QtGui.QWidget()
        self.mosaicTab.setObjectName(_fromUtf8("mosaicTab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.mosaicTab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.mosaicFrame = QtGui.QFrame(self.mosaicTab)
        self.mosaicFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mosaicFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.mosaicFrame.setObjectName(_fromUtf8("mosaicFrame"))
        self.horizontalLayout_2.addWidget(self.mosaicFrame)
        self.widget = QtGui.QWidget(self.mosaicTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 100000))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.positionsGroupBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positionsGroupBox.sizePolicy().hasHeightForWidth())
        self.positionsGroupBox.setSizePolicy(sizePolicy)
        self.positionsGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.positionsGroupBox.setMaximumSize(QtCore.QSize(10000, 10000))
        self.positionsGroupBox.setObjectName(_fromUtf8("positionsGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.positionsGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.positionsFrame = QtGui.QFrame(self.positionsGroupBox)
        self.positionsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.positionsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.positionsFrame.setObjectName(_fromUtf8("positionsFrame"))
        self.verticalLayout_4.addWidget(self.positionsFrame)
        self.verticalLayout_2.addWidget(self.positionsGroupBox)
        self.objectivesGroupBox = QtGui.QGroupBox(self.widget)
        self.objectivesGroupBox.setMinimumSize(QtCore.QSize(250, 50))
        self.objectivesGroupBox.setMaximumSize(QtCore.QSize(300, 300))
        self.objectivesGroupBox.setObjectName(_fromUtf8("objectivesGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.objectivesGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.objectivesFrame = QtGui.QFrame(self.objectivesGroupBox)
        self.objectivesFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.objectivesFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.objectivesFrame.setObjectName(_fromUtf8("objectivesFrame"))
        self.verticalLayout_3.addWidget(self.objectivesFrame)
        self.verticalLayout_2.addWidget(self.objectivesGroupBox)
        self.horizontalLayout_2.addWidget(self.widget)
        self.tabWidget.addTab(self.mosaicTab, _fromUtf8(""))
        self.sectionsTab = QtGui.QWidget()
        self.sectionsTab.setObjectName(_fromUtf8("sectionsTab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.sectionsTab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sectionsDisplayFrame = QtGui.QFrame(self.sectionsTab)
        self.sectionsDisplayFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sectionsDisplayFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sectionsDisplayFrame.setObjectName(_fromUtf8("sectionsDisplayFrame"))
        self.horizontalLayout_3.addWidget(self.sectionsDisplayFrame)
        self.sectionsWidget = QtGui.QWidget(self.sectionsTab)
        self.sectionsWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.sectionsWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.sectionsWidget.setObjectName(_fromUtf8("sectionsWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.sectionsWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.sectionsGroupBox = QtGui.QGroupBox(self.sectionsWidget)
        self.sectionsGroupBox.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.sectionsGroupBox.setObjectName(_fromUtf8("sectionsGroupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.sectionsGroupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.sectionsScrollArea = QtGui.QScrollArea(self.sectionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectionsScrollArea.sizePolicy().hasHeightForWidth())
        self.sectionsScrollArea.setSizePolicy(sizePolicy)
        self.sectionsScrollArea.setWidgetResizable(True)
        self.sectionsScrollArea.setObjectName(_fromUtf8("sectionsScrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.sectionsScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.sectionsScrollArea)
        self.verticalLayout_5.addWidget(self.sectionsGroupBox)
        self.sectionViewSettingsGroupBox = QtGui.QGroupBox(self.sectionsWidget)
        self.sectionViewSettingsGroupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.sectionViewSettingsGroupBox.setObjectName(_fromUtf8("sectionViewSettingsGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.sectionViewSettingsGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.thresholdLabel = QtGui.QLabel(self.sectionViewSettingsGroupBox)
        self.thresholdLabel.setObjectName(_fromUtf8("thresholdLabel"))
        self.gridLayout.addWidget(self.thresholdLabel, 1, 0, 1, 1)
        self.foregroundOpacitySlider = QtGui.QSlider(self.sectionViewSettingsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foregroundOpacitySlider.sizePolicy().hasHeightForWidth())
        self.foregroundOpacitySlider.setSizePolicy(sizePolicy)
        self.foregroundOpacitySlider.setMaximum(100)
        self.foregroundOpacitySlider.setProperty("value", 50)
        self.foregroundOpacitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.foregroundOpacitySlider.setObjectName(_fromUtf8("foregroundOpacitySlider"))
        self.gridLayout.addWidget(self.foregroundOpacitySlider, 4, 1, 1, 1)
        self.moveAllSectionsCheckBox = QtGui.QCheckBox(self.sectionViewSettingsGroupBox)
        self.moveAllSectionsCheckBox.setObjectName(_fromUtf8("moveAllSectionsCheckBox"))
        self.gridLayout.addWidget(self.moveAllSectionsCheckBox, 0, 0, 1, 1)
        self.foregroundOpacityLabel = QtGui.QLabel(self.sectionViewSettingsGroupBox)
        self.foregroundOpacityLabel.setObjectName(_fromUtf8("foregroundOpacityLabel"))
        self.gridLayout.addWidget(self.foregroundOpacityLabel, 4, 0, 1, 1)
        self.showFeaturesCheckBox = QtGui.QCheckBox(self.sectionViewSettingsGroupBox)
        self.showFeaturesCheckBox.setObjectName(_fromUtf8("showFeaturesCheckBox"))
        self.gridLayout.addWidget(self.showFeaturesCheckBox, 0, 1, 1, 1)
        self.backgroundLabel = QtGui.QLabel(self.sectionViewSettingsGroupBox)
        self.backgroundLabel.setObjectName(_fromUtf8("backgroundLabel"))
        self.gridLayout.addWidget(self.backgroundLabel, 2, 0, 1, 1)
        self.backgroundComboBox = QtGui.QComboBox(self.sectionViewSettingsGroupBox)
        self.backgroundComboBox.setObjectName(_fromUtf8("backgroundComboBox"))
        self.backgroundComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.backgroundComboBox, 2, 1, 1, 1)
        self.thresholdSlider = QtGui.QSlider(self.sectionViewSettingsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdSlider.sizePolicy().hasHeightForWidth())
        self.thresholdSlider.setSizePolicy(sizePolicy)
        self.thresholdSlider.setMaximum(100)
        self.thresholdSlider.setProperty("value", 50)
        self.thresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.thresholdSlider.setObjectName(_fromUtf8("thresholdSlider"))
        self.gridLayout.addWidget(self.thresholdSlider, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.sectionViewSettingsGroupBox)
        self.horizontalLayout_3.addWidget(self.sectionsWidget)
        self.tabWidget.addTab(self.sectionsTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mosaicLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mosaicLabel.sizePolicy().hasHeightForWidth())
        self.mosaicLabel.setSizePolicy(sizePolicy)
        self.mosaicLabel.setObjectName(_fromUtf8("mosaicLabel"))
        self.horizontalLayout.addWidget(self.mosaicLabel)
        self.xLabel = QtGui.QLabel(self.centralwidget)
        self.xLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xLabel.setObjectName(_fromUtf8("xLabel"))
        self.horizontalLayout.addWidget(self.xLabel)
        self.xSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.xSpinBox.setMinimum(1)
        self.xSpinBox.setProperty("value", 5)
        self.xSpinBox.setObjectName(_fromUtf8("xSpinBox"))
        self.horizontalLayout.addWidget(self.xSpinBox)
        self.yLabel = QtGui.QLabel(self.centralwidget)
        self.yLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yLabel.setObjectName(_fromUtf8("yLabel"))
        self.horizontalLayout.addWidget(self.yLabel)
        self.ySpinBox = QtGui.QSpinBox(self.centralwidget)
        self.ySpinBox.setMinimum(1)
        self.ySpinBox.setProperty("value", 3)
        self.ySpinBox.setObjectName(_fromUtf8("ySpinBox"))
        self.horizontalLayout.addWidget(self.ySpinBox)
        self.abortButton = QtGui.QPushButton(self.centralwidget)
        self.abortButton.setObjectName(_fromUtf8("abortButton"))
        self.horizontalLayout.addWidget(self.abortButton)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.magComboBox = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magComboBox.sizePolicy().hasHeightForWidth())
        self.magComboBox.setSizePolicy(sizePolicy)
        self.magComboBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.magComboBox.setEditable(False)
        self.magComboBox.setObjectName(_fromUtf8("magComboBox"))
        self.horizontalLayout.addWidget(self.magComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 937, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionDisconnect = QtGui.QAction(MainWindow)
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.actionSave_Positions = QtGui.QAction(MainWindow)
        self.actionSave_Positions.setObjectName(_fromUtf8("actionSave_Positions"))
        self.actionSave_Mosaic = QtGui.QAction(MainWindow)
        self.actionSave_Mosaic.setObjectName(_fromUtf8("actionSave_Mosaic"))
        self.actionSet_Working_Directory = QtGui.QAction(MainWindow)
        self.actionSet_Working_Directory.setObjectName(_fromUtf8("actionSet_Working_Directory"))
        self.actionLoad_Mosaic = QtGui.QAction(MainWindow)
        self.actionLoad_Mosaic.setObjectName(_fromUtf8("actionLoad_Mosaic"))
        self.actionDelete_Images = QtGui.QAction(MainWindow)
        self.actionDelete_Images.setObjectName(_fromUtf8("actionDelete_Images"))
        self.actionLoad_Positions = QtGui.QAction(MainWindow)
        self.actionLoad_Positions.setObjectName(_fromUtf8("actionLoad_Positions"))
        self.actionSave_Snapshot = QtGui.QAction(MainWindow)
        self.actionSave_Snapshot.setObjectName(_fromUtf8("actionSave_Snapshot"))
        self.actionLoad_Dax = QtGui.QAction(MainWindow)
        self.actionLoad_Dax.setObjectName(_fromUtf8("actionLoad_Dax"))
        self.menuFile.addAction(self.actionSet_Working_Directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDelete_Images)
        self.menuFile.addAction(self.actionLoad_Dax)
        self.menuFile.addAction(self.actionLoad_Mosaic)
        self.menuFile.addAction(self.actionLoad_Positions)
        self.menuFile.addAction(self.actionSave_Mosaic)
        self.menuFile.addAction(self.actionSave_Positions)
        self.menuFile.addAction(self.actionSave_Snapshot)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Steve", None))
        self.positionsGroupBox.setTitle(_translate("MainWindow", "Positions", None))
        self.objectivesGroupBox.setTitle(_translate("MainWindow", "Objective Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mosaicTab), _translate("MainWindow", "Mosaic", None))
        self.sectionsGroupBox.setTitle(_translate("MainWindow", "Sections", None))
        self.sectionViewSettingsGroupBox.setTitle(_translate("MainWindow", "Section View Settings", None))
        self.thresholdLabel.setText(_translate("MainWindow", "Threshold", None))
        self.moveAllSectionsCheckBox.setText(_translate("MainWindow", "Move All Sections", None))
        self.foregroundOpacityLabel.setText(_translate("MainWindow", "Section Opacity", None))
        self.showFeaturesCheckBox.setText(_translate("MainWindow", "Show Features", None))
        self.backgroundLabel.setText(_translate("MainWindow", "Background Type", None))
        self.backgroundComboBox.setItemText(0, _translate("MainWindow", "Mean", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sectionsTab), _translate("MainWindow", "Sections", None))
        self.mosaicLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.xLabel.setText(_translate("MainWindow", "# X:", None))
        self.yLabel.setText(_translate("MainWindow", "# Y:", None))
        self.abortButton.setText(_translate("MainWindow", "Abort Acquistion", None))
        self.label.setText(_translate("MainWindow", "Current Objective:", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionConnect.setText(_translate("MainWindow", "Connect", None))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect", None))
        self.actionSave_Positions.setText(_translate("MainWindow", "Save Positions", None))
        self.actionSave_Mosaic.setText(_translate("MainWindow", "Save Mosaic", None))
        self.actionSet_Working_Directory.setText(_translate("MainWindow", "Set Working Directory", None))
        self.actionLoad_Mosaic.setText(_translate("MainWindow", "Load Mosaic", None))
        self.actionDelete_Images.setText(_translate("MainWindow", "Delete Images", None))
        self.actionLoad_Positions.setText(_translate("MainWindow", "Load Positions", None))
        self.actionSave_Snapshot.setText(_translate("MainWindow", "Save Snapshot", None))
        self.actionLoad_Dax.setText(_translate("MainWindow", "Load Dax", None))

