# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera-params-detached.ui'
#
# Created: Fri Nov 22 08:34:11 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName(_fromUtf8("GroupBox"))
        GroupBox.resize(387, 94)
        GroupBox.setMinimumSize(QtCore.QSize(387, 94))
        self.horizontalLayout = QtGui.QHBoxLayout(GroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_2 = QtGui.QWidget(GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(361, 61))
        self.widget_2.setMaximumSize(QtCore.QSize(361, 61))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.temperatureText = QtGui.QLabel(self.widget_2)
        self.temperatureText.setGeometry(QtCore.QRect(303, 43, 50, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperatureText.sizePolicy().hasHeightForWidth())
        self.temperatureText.setSizePolicy(sizePolicy)
        self.temperatureText.setMinimumSize(QtCore.QSize(50, 0))
        self.temperatureText.setMaximumSize(QtCore.QSize(50, 16777215))
        self.temperatureText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.temperatureText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temperatureText.setObjectName(_fromUtf8("temperatureText"))
        self.FPSLabel = QtGui.QLabel(self.widget_2)
        self.FPSLabel.setGeometry(QtCore.QRect(213, 23, 100, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FPSLabel.sizePolicy().hasHeightForWidth())
        self.FPSLabel.setSizePolicy(sizePolicy)
        self.FPSLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.FPSLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.FPSLabel.setObjectName(_fromUtf8("FPSLabel"))
        self.pictureSizeLabel = QtGui.QLabel(self.widget_2)
        self.pictureSizeLabel.setGeometry(QtCore.QRect(3, 43, 100, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pictureSizeLabel.sizePolicy().hasHeightForWidth())
        self.pictureSizeLabel.setSizePolicy(sizePolicy)
        self.pictureSizeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.pictureSizeLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pictureSizeLabel.setObjectName(_fromUtf8("pictureSizeLabel"))
        self.preampGainText = QtGui.QLabel(self.widget_2)
        self.preampGainText.setGeometry(QtCore.QRect(109, 23, 91, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preampGainText.sizePolicy().hasHeightForWidth())
        self.preampGainText.setSizePolicy(sizePolicy)
        self.preampGainText.setMinimumSize(QtCore.QSize(50, 0))
        self.preampGainText.setMaximumSize(QtCore.QSize(100, 16777215))
        self.preampGainText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.preampGainText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.preampGainText.setObjectName(_fromUtf8("preampGainText"))
        self.temperatureLabel = QtGui.QLabel(self.widget_2)
        self.temperatureLabel.setGeometry(QtCore.QRect(213, 43, 100, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperatureLabel.sizePolicy().hasHeightForWidth())
        self.temperatureLabel.setSizePolicy(sizePolicy)
        self.temperatureLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.temperatureLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.temperatureLabel.setObjectName(_fromUtf8("temperatureLabel"))
        self.FPSText = QtGui.QLabel(self.widget_2)
        self.FPSText.setGeometry(QtCore.QRect(303, 23, 50, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FPSText.sizePolicy().hasHeightForWidth())
        self.FPSText.setSizePolicy(sizePolicy)
        self.FPSText.setMinimumSize(QtCore.QSize(50, 0))
        self.FPSText.setMaximumSize(QtCore.QSize(50, 16777215))
        self.FPSText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.FPSText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FPSText.setObjectName(_fromUtf8("FPSText"))
        self.EMCCDSlider = QtGui.QSlider(self.widget_2)
        self.EMCCDSlider.setGeometry(QtCore.QRect(106, 0, 100, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EMCCDSlider.sizePolicy().hasHeightForWidth())
        self.EMCCDSlider.setSizePolicy(sizePolicy)
        self.EMCCDSlider.setMinimumSize(QtCore.QSize(100, 0))
        self.EMCCDSlider.setMaximumSize(QtCore.QSize(100, 16777215))
        self.EMCCDSlider.setMaximum(100)
        self.EMCCDSlider.setProperty("value", 0)
        self.EMCCDSlider.setOrientation(QtCore.Qt.Horizontal)
        self.EMCCDSlider.setObjectName(_fromUtf8("EMCCDSlider"))
        self.exposureTimeText = QtGui.QLabel(self.widget_2)
        self.exposureTimeText.setGeometry(QtCore.QRect(303, 3, 50, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureTimeText.sizePolicy().hasHeightForWidth())
        self.exposureTimeText.setSizePolicy(sizePolicy)
        self.exposureTimeText.setMinimumSize(QtCore.QSize(50, 0))
        self.exposureTimeText.setMaximumSize(QtCore.QSize(50, 16777215))
        self.exposureTimeText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exposureTimeText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exposureTimeText.setObjectName(_fromUtf8("exposureTimeText"))
        self.preampGainLabel = QtGui.QLabel(self.widget_2)
        self.preampGainLabel.setGeometry(QtCore.QRect(3, 23, 100, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preampGainLabel.sizePolicy().hasHeightForWidth())
        self.preampGainLabel.setSizePolicy(sizePolicy)
        self.preampGainLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.preampGainLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.preampGainLabel.setObjectName(_fromUtf8("preampGainLabel"))
        self.EMCCDLabel = QtGui.QLabel(self.widget_2)
        self.EMCCDLabel.setGeometry(QtCore.QRect(3, 3, 100, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EMCCDLabel.sizePolicy().hasHeightForWidth())
        self.EMCCDLabel.setSizePolicy(sizePolicy)
        self.EMCCDLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.EMCCDLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.EMCCDLabel.setObjectName(_fromUtf8("EMCCDLabel"))
        self.exposureTimeLabel = QtGui.QLabel(self.widget_2)
        self.exposureTimeLabel.setGeometry(QtCore.QRect(213, 3, 100, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureTimeLabel.sizePolicy().hasHeightForWidth())
        self.exposureTimeLabel.setSizePolicy(sizePolicy)
        self.exposureTimeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.exposureTimeLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.exposureTimeLabel.setObjectName(_fromUtf8("exposureTimeLabel"))
        self.pictureSizeText = QtGui.QLabel(self.widget_2)
        self.pictureSizeText.setGeometry(QtCore.QRect(109, 43, 91, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pictureSizeText.sizePolicy().hasHeightForWidth())
        self.pictureSizeText.setSizePolicy(sizePolicy)
        self.pictureSizeText.setMinimumSize(QtCore.QSize(50, 0))
        self.pictureSizeText.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pictureSizeText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pictureSizeText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pictureSizeText.setObjectName(_fromUtf8("pictureSizeText"))
        self.horizontalLayout.addWidget(self.widget_2)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox", None))
        GroupBox.setTitle(_translate("GroupBox", "Camera", None))
        self.temperatureText.setText(_translate("GroupBox", "0", None))
        self.FPSLabel.setText(_translate("GroupBox", "FPS (Hz):", None))
        self.pictureSizeLabel.setText(_translate("GroupBox", "Picture Size:", None))
        self.preampGainText.setText(_translate("GroupBox", "0", None))
        self.temperatureLabel.setText(_translate("GroupBox", "Temperature (C):", None))
        self.FPSText.setText(_translate("GroupBox", "0", None))
        self.exposureTimeText.setText(_translate("GroupBox", "0", None))
        self.preampGainLabel.setText(_translate("GroupBox", "Preamp Gain:", None))
        self.EMCCDLabel.setText(_translate("GroupBox", "EMCCD Gain: 0", None))
        self.exposureTimeLabel.setText(_translate("GroupBox", "Exposure Time (s):", None))
        self.pictureSizeText.setText(_translate("GroupBox", "0", None))

