# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera-params-detached.ui'
#
# Created: Wed Jan 01 11:02:29 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName(_fromUtf8("GroupBox"))
        GroupBox.resize(387, 94)
        GroupBox.setMinimumSize(QtCore.QSize(387, 94))
        self.gridLayout = QtGui.QGridLayout(GroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.exposureTimeLabel = QtGui.QLabel(GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureTimeLabel.sizePolicy().hasHeightForWidth())
        self.exposureTimeLabel.setSizePolicy(sizePolicy)
        self.exposureTimeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.exposureTimeLabel.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.exposureTimeLabel.setObjectName(_fromUtf8("exposureTimeLabel"))
        self.gridLayout.addWidget(self.exposureTimeLabel, 0, 0, 1, 1)
        self.exposureTimeText = QtGui.QLabel(GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureTimeText.sizePolicy().hasHeightForWidth())
        self.exposureTimeText.setSizePolicy(sizePolicy)
        self.exposureTimeText.setMinimumSize(QtCore.QSize(50, 0))
        self.exposureTimeText.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.exposureTimeText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exposureTimeText.setFrameShape(QtGui.QFrame.NoFrame)
        self.exposureTimeText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exposureTimeText.setObjectName(_fromUtf8("exposureTimeText"))
        self.gridLayout.addWidget(self.exposureTimeText, 0, 1, 1, 1)
        self.temperatureLabel = QtGui.QLabel(GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperatureLabel.sizePolicy().hasHeightForWidth())
        self.temperatureLabel.setSizePolicy(sizePolicy)
        self.temperatureLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.temperatureLabel.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.temperatureLabel.setObjectName(_fromUtf8("temperatureLabel"))
        self.gridLayout.addWidget(self.temperatureLabel, 0, 2, 1, 1)
        self.temperatureText = QtGui.QLabel(GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperatureText.sizePolicy().hasHeightForWidth())
        self.temperatureText.setSizePolicy(sizePolicy)
        self.temperatureText.setMinimumSize(QtCore.QSize(50, 0))
        self.temperatureText.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.temperatureText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.temperatureText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temperatureText.setObjectName(_fromUtf8("temperatureText"))
        self.gridLayout.addWidget(self.temperatureText, 0, 3, 1, 1)
        self.FPSLabel = QtGui.QLabel(GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FPSLabel.sizePolicy().hasHeightForWidth())
        self.FPSLabel.setSizePolicy(sizePolicy)
        self.FPSLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.FPSLabel.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.FPSLabel.setObjectName(_fromUtf8("FPSLabel"))
        self.gridLayout.addWidget(self.FPSLabel, 1, 0, 1, 1)
        self.FPSText = QtGui.QLabel(GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FPSText.sizePolicy().hasHeightForWidth())
        self.FPSText.setSizePolicy(sizePolicy)
        self.FPSText.setMinimumSize(QtCore.QSize(50, 0))
        self.FPSText.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.FPSText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.FPSText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FPSText.setObjectName(_fromUtf8("FPSText"))
        self.gridLayout.addWidget(self.FPSText, 1, 1, 1, 1)
        self.EMCCDLabel = QtGui.QLabel(GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EMCCDLabel.sizePolicy().hasHeightForWidth())
        self.EMCCDLabel.setSizePolicy(sizePolicy)
        self.EMCCDLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.EMCCDLabel.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.EMCCDLabel.setObjectName(_fromUtf8("EMCCDLabel"))
        self.gridLayout.addWidget(self.EMCCDLabel, 1, 2, 1, 1)
        self.EMCCDSlider = QtGui.QSlider(GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EMCCDSlider.sizePolicy().hasHeightForWidth())
        self.EMCCDSlider.setSizePolicy(sizePolicy)
        self.EMCCDSlider.setMinimumSize(QtCore.QSize(100, 0))
        self.EMCCDSlider.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.EMCCDSlider.setMaximum(100)
        self.EMCCDSlider.setProperty("value", 0)
        self.EMCCDSlider.setOrientation(QtCore.Qt.Horizontal)
        self.EMCCDSlider.setObjectName(_fromUtf8("EMCCDSlider"))
        self.gridLayout.addWidget(self.EMCCDSlider, 1, 3, 1, 1)
        self.pictureSizeLabel = QtGui.QLabel(GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pictureSizeLabel.sizePolicy().hasHeightForWidth())
        self.pictureSizeLabel.setSizePolicy(sizePolicy)
        self.pictureSizeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.pictureSizeLabel.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.pictureSizeLabel.setObjectName(_fromUtf8("pictureSizeLabel"))
        self.gridLayout.addWidget(self.pictureSizeLabel, 2, 0, 1, 1)
        self.pictureSizeText = QtGui.QLabel(GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pictureSizeText.sizePolicy().hasHeightForWidth())
        self.pictureSizeText.setSizePolicy(sizePolicy)
        self.pictureSizeText.setMinimumSize(QtCore.QSize(50, 0))
        self.pictureSizeText.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.pictureSizeText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pictureSizeText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pictureSizeText.setObjectName(_fromUtf8("pictureSizeText"))
        self.gridLayout.addWidget(self.pictureSizeText, 2, 1, 1, 1)
        self.preampGainLabel = QtGui.QLabel(GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preampGainLabel.sizePolicy().hasHeightForWidth())
        self.preampGainLabel.setSizePolicy(sizePolicy)
        self.preampGainLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.preampGainLabel.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.preampGainLabel.setObjectName(_fromUtf8("preampGainLabel"))
        self.gridLayout.addWidget(self.preampGainLabel, 2, 2, 1, 1)
        self.preampGainText = QtGui.QLabel(GroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preampGainText.sizePolicy().hasHeightForWidth())
        self.preampGainText.setSizePolicy(sizePolicy)
        self.preampGainText.setMinimumSize(QtCore.QSize(50, 0))
        self.preampGainText.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.preampGainText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.preampGainText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.preampGainText.setObjectName(_fromUtf8("preampGainText"))
        self.gridLayout.addWidget(self.preampGainText, 2, 3, 1, 1)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox", None))
        GroupBox.setTitle(_translate("GroupBox", "Camera", None))
        self.exposureTimeLabel.setText(_translate("GroupBox", "Exposure Time (s):", None))
        self.exposureTimeText.setText(_translate("GroupBox", "0", None))
        self.temperatureLabel.setText(_translate("GroupBox", "Temperature (C):", None))
        self.temperatureText.setText(_translate("GroupBox", "0", None))
        self.FPSLabel.setText(_translate("GroupBox", "FPS (Hz):", None))
        self.FPSText.setText(_translate("GroupBox", "0", None))
        self.EMCCDLabel.setText(_translate("GroupBox", "EMCCD Gain: 0", None))
        self.pictureSizeLabel.setText(_translate("GroupBox", "Picture Size:", None))
        self.pictureSizeText.setText(_translate("GroupBox", "0", None))
        self.preampGainLabel.setText(_translate("GroupBox", "Preamp Gain:", None))
        self.preampGainText.setText(_translate("GroupBox", "0", None))

