# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hal4000-detached.ui'
#
# Created: Wed Feb 26 13:55:06 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(239, 698)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(239, 0))
        MainWindow.setMaximumSize(QtCore.QSize(239, 10000))
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../HAL-4000.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(1000, 10000))
        self.centralwidget.setAcceptDrops(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setMargin(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mainWidget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy)
        self.mainWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.mainWidget.setMaximumSize(QtCore.QSize(1000, 10000))
        self.mainWidget.setObjectName(_fromUtf8("mainWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.mainWidget)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setMargin(2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.settingsGroupBox = QtGui.QGroupBox(self.mainWidget)
        self.settingsGroupBox.setMinimumSize(QtCore.QSize(50, 40))
        self.settingsGroupBox.setMaximumSize(QtCore.QSize(231, 16777215))
        self.settingsGroupBox.setObjectName(_fromUtf8("settingsGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.settingsGroupBox)
        self.gridLayout.setMargin(2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.settingsScrollArea = QtGui.QScrollArea(self.settingsGroupBox)
        self.settingsScrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.settingsScrollArea.setWidgetResizable(True)
        self.settingsScrollArea.setObjectName(_fromUtf8("settingsScrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 225, 124))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.settingsScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.settingsScrollArea, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.settingsGroupBox)
        self.filmGroupBox = QtGui.QGroupBox(self.mainWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filmGroupBox.sizePolicy().hasHeightForWidth())
        self.filmGroupBox.setSizePolicy(sizePolicy)
        self.filmGroupBox.setMinimumSize(QtCore.QSize(231, 261))
        self.filmGroupBox.setObjectName(_fromUtf8("filmGroupBox"))
        self.directoryText = QtGui.QLabel(self.filmGroupBox)
        self.directoryText.setGeometry(QtCore.QRect(30, 60, 191, 16))
        self.directoryText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.directoryText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.directoryText.setObjectName(_fromUtf8("directoryText"))
        self.filenameEdit = QtGui.QLineEdit(self.filmGroupBox)
        self.filenameEdit.setGeometry(QtCore.QRect(9, 102, 81, 20))
        self.filenameEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.filenameEdit.setObjectName(_fromUtf8("filenameEdit"))
        self.framesLabel = QtGui.QLabel(self.filmGroupBox)
        self.framesLabel.setGeometry(QtCore.QRect(10, 210, 51, 16))
        self.framesLabel.setObjectName(_fromUtf8("framesLabel"))
        self.saveMovieCheckBox = QtGui.QCheckBox(self.filmGroupBox)
        self.saveMovieCheckBox.setGeometry(QtCore.QRect(120, 230, 81, 19))
        self.saveMovieCheckBox.setChecked(True)
        self.saveMovieCheckBox.setObjectName(_fromUtf8("saveMovieCheckBox"))
        self.sizeLabel = QtGui.QLabel(self.filmGroupBox)
        self.sizeLabel.setGeometry(QtCore.QRect(120, 210, 31, 16))
        self.sizeLabel.setObjectName(_fromUtf8("sizeLabel"))
        self.modeComboBox = QtGui.QComboBox(self.filmGroupBox)
        self.modeComboBox.setGeometry(QtCore.QRect(50, 150, 91, 22))
        self.modeComboBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.modeComboBox.setObjectName(_fromUtf8("modeComboBox"))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.lengthLabel = QtGui.QLabel(self.filmGroupBox)
        self.lengthLabel.setGeometry(QtCore.QRect(10, 183, 46, 14))
        self.lengthLabel.setObjectName(_fromUtf8("lengthLabel"))
        self.modeLabel = QtGui.QLabel(self.filmGroupBox)
        self.modeLabel.setGeometry(QtCore.QRect(10, 154, 46, 14))
        self.modeLabel.setObjectName(_fromUtf8("modeLabel"))
        self.directoryLabel = QtGui.QLabel(self.filmGroupBox)
        self.directoryLabel.setGeometry(QtCore.QRect(10, 40, 211, 16))
        self.directoryLabel.setObjectName(_fromUtf8("directoryLabel"))
        self.framesText = QtGui.QLabel(self.filmGroupBox)
        self.framesText.setGeometry(QtCore.QRect(47, 210, 61, 20))
        self.framesText.setText(_fromUtf8(""))
        self.framesText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.framesText.setObjectName(_fromUtf8("framesText"))
        self.sizeText = QtGui.QLabel(self.filmGroupBox)
        self.sizeText.setGeometry(QtCore.QRect(147, 210, 71, 20))
        self.sizeText.setText(_fromUtf8(""))
        self.sizeText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sizeText.setObjectName(_fromUtf8("sizeText"))
        self.autoShuttersCheckBox = QtGui.QCheckBox(self.filmGroupBox)
        self.autoShuttersCheckBox.setGeometry(QtCore.QRect(10, 230, 101, 19))
        self.autoShuttersCheckBox.setChecked(True)
        self.autoShuttersCheckBox.setObjectName(_fromUtf8("autoShuttersCheckBox"))
        self.shuttersLabels = QtGui.QLabel(self.filmGroupBox)
        self.shuttersLabels.setGeometry(QtCore.QRect(10, 21, 101, 16))
        self.shuttersLabels.setObjectName(_fromUtf8("shuttersLabels"))
        self.shuttersText = QtGui.QLabel(self.filmGroupBox)
        self.shuttersText.setGeometry(QtCore.QRect(110, 20, 111, 20))
        self.shuttersText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shuttersText.setText(_fromUtf8(""))
        self.shuttersText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shuttersText.setObjectName(_fromUtf8("shuttersText"))
        self.filenameLabel = QtGui.QLabel(self.filmGroupBox)
        self.filenameLabel.setGeometry(QtCore.QRect(20, 127, 201, 20))
        self.filenameLabel.setText(_fromUtf8(""))
        self.filenameLabel.setObjectName(_fromUtf8("filenameLabel"))
        self.indexSpinBox = QtGui.QSpinBox(self.filmGroupBox)
        self.indexSpinBox.setGeometry(QtCore.QRect(91, 101, 45, 22))
        self.indexSpinBox.setMinimum(1)
        self.indexSpinBox.setMaximum(9999)
        self.indexSpinBox.setObjectName(_fromUtf8("indexSpinBox"))
        self.extensionComboBox = QtGui.QComboBox(self.filmGroupBox)
        self.extensionComboBox.setGeometry(QtCore.QRect(137, 101, 45, 22))
        self.extensionComboBox.setObjectName(_fromUtf8("extensionComboBox"))
        self.autoIncCheckBox = QtGui.QCheckBox(self.filmGroupBox)
        self.autoIncCheckBox.setGeometry(QtCore.QRect(10, 79, 201, 19))
        self.autoIncCheckBox.setChecked(True)
        self.autoIncCheckBox.setObjectName(_fromUtf8("autoIncCheckBox"))
        self.lengthSpinBox = QtGui.QSpinBox(self.filmGroupBox)
        self.lengthSpinBox.setGeometry(QtCore.QRect(60, 180, 81, 22))
        self.lengthSpinBox.setMaximum(1000000)
        self.lengthSpinBox.setObjectName(_fromUtf8("lengthSpinBox"))
        self.filetypeComboBox = QtGui.QComboBox(self.filmGroupBox)
        self.filetypeComboBox.setGeometry(QtCore.QRect(183, 101, 45, 22))
        self.filetypeComboBox.setObjectName(_fromUtf8("filetypeComboBox"))
        self.verticalLayout.addWidget(self.filmGroupBox)
        self.notesGroupBox = QtGui.QGroupBox(self.mainWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesGroupBox.sizePolicy().hasHeightForWidth())
        self.notesGroupBox.setSizePolicy(sizePolicy)
        self.notesGroupBox.setMinimumSize(QtCore.QSize(50, 200))
        self.notesGroupBox.setMaximumSize(QtCore.QSize(231, 200))
        self.notesGroupBox.setObjectName(_fromUtf8("notesGroupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.notesGroupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.notesEdit = QtGui.QTextEdit(self.notesGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesEdit.sizePolicy().hasHeightForWidth())
        self.notesEdit.setSizePolicy(sizePolicy)
        self.notesEdit.setMinimumSize(QtCore.QSize(20, 37))
        self.notesEdit.setMaximumSize(QtCore.QSize(10000, 10000))
        self.notesEdit.setObjectName(_fromUtf8("notesEdit"))
        self.horizontalLayout_3.addWidget(self.notesEdit)
        self.verticalLayout.addWidget(self.notesGroupBox)
        self.widget = QtGui.QWidget(self.mainWidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setMargin(2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(139, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.recordButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordButton.sizePolicy().hasHeightForWidth())
        self.recordButton.setSizePolicy(sizePolicy)
        self.recordButton.setMaximumSize(QtCore.QSize(75, 23))
        self.recordButton.setObjectName(_fromUtf8("recordButton"))
        self.horizontalLayout_2.addWidget(self.recordButton)
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout_2.addWidget(self.mainWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 239, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionShutter = QtGui.QAction(MainWindow)
        self.actionShutter.setObjectName(_fromUtf8("actionShutter"))
        self.actionDirectory = QtGui.QAction(MainWindow)
        self.actionDirectory.setObjectName(_fromUtf8("actionDirectory"))
        self.actionIllumination = QtGui.QAction(MainWindow)
        self.actionIllumination.setObjectName(_fromUtf8("actionIllumination"))
        self.actionStage = QtGui.QAction(MainWindow)
        self.actionStage.setObjectName(_fromUtf8("actionStage"))
        self.actionFocus_Lock = QtGui.QAction(MainWindow)
        self.actionFocus_Lock.setObjectName(_fromUtf8("actionFocus_Lock"))
        self.actionSpot_Counter = QtGui.QAction(MainWindow)
        self.actionSpot_Counter.setObjectName(_fromUtf8("actionSpot_Counter"))
        self.actionSwitch_Test = QtGui.QAction(MainWindow)
        self.actionSwitch_Test.setObjectName(_fromUtf8("actionSwitch_Test"))
        self.actionMisc_Controls = QtGui.QAction(MainWindow)
        self.actionMisc_Controls.setObjectName(_fromUtf8("actionMisc_Controls"))
        self.actionProgression = QtGui.QAction(MainWindow)
        self.actionProgression.setObjectName(_fromUtf8("actionProgression"))
        self.actionDisconnect = QtGui.QAction(MainWindow)
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionShutter)
        self.menuFile.addAction(self.actionDirectory)
        self.menuFile.addAction(self.actionDisconnect)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "HAL-4000", None))
        self.settingsGroupBox.setTitle(_translate("MainWindow", "Settings", None))
        self.filmGroupBox.setTitle(_translate("MainWindow", "Film", None))
        self.directoryText.setText(_translate("MainWindow", "TextLabel", None))
        self.framesLabel.setText(_translate("MainWindow", "Frames:", None))
        self.saveMovieCheckBox.setText(_translate("MainWindow", "Save Movie", None))
        self.sizeLabel.setText(_translate("MainWindow", "Size:", None))
        self.modeComboBox.setItemText(0, _translate("MainWindow", "Run Till Abort", None))
        self.modeComboBox.setItemText(1, _translate("MainWindow", "Fixed Length", None))
        self.lengthLabel.setText(_translate("MainWindow", "Length:", None))
        self.modeLabel.setText(_translate("MainWindow", "Mode:", None))
        self.directoryLabel.setText(_translate("MainWindow", "Directory:", None))
        self.autoShuttersCheckBox.setText(_translate("MainWindow", "Run Shutters", None))
        self.shuttersLabels.setText(_translate("MainWindow", "Shutter Sequence:", None))
        self.autoIncCheckBox.setText(_translate("MainWindow", "Increment Automatically", None))
        self.notesGroupBox.setTitle(_translate("MainWindow", "Notes", None))
        self.recordButton.setText(_translate("MainWindow", "Record", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionSettings.setText(_translate("MainWindow", "New Settings", None))
        self.actionShutter.setText(_translate("MainWindow", "New Shutter Sequence", None))
        self.actionDirectory.setText(_translate("MainWindow", "Set Working Directory", None))
        self.actionIllumination.setText(_translate("MainWindow", "Illumination", None))
        self.actionStage.setText(_translate("MainWindow", "Stage", None))
        self.actionFocus_Lock.setText(_translate("MainWindow", "Focus Lock", None))
        self.actionSpot_Counter.setText(_translate("MainWindow", "Spot Counter", None))
        self.actionSwitch_Test.setText(_translate("MainWindow", "Switch Test", None))
        self.actionMisc_Controls.setText(_translate("MainWindow", "Misc. Controls", None))
        self.actionProgression.setText(_translate("MainWindow", "Progressions", None))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect", None))

