# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nstorm-misc.ui'
#
# Created: Tue Apr 14 08:52:49 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(428, 232)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(428, 232))
        Dialog.setMaximumSize(QtCore.QSize(428, 232))
        self.TIRFgroupBox = QtGui.QGroupBox(Dialog)
        self.TIRFgroupBox.setGeometry(QtCore.QRect(9, 9, 301, 111))
        self.TIRFgroupBox.setObjectName(_fromUtf8("TIRFgroupBox"))
        self.leftLargeButton = QtGui.QPushButton(self.TIRFgroupBox)
        self.leftLargeButton.setGeometry(QtCore.QRect(53, 20, 31, 24))
        self.leftLargeButton.setObjectName(_fromUtf8("leftLargeButton"))
        self.rightSmallButton = QtGui.QPushButton(self.TIRFgroupBox)
        self.rightSmallButton.setGeometry(QtCore.QRect(106, 20, 21, 24))
        self.rightSmallButton.setObjectName(_fromUtf8("rightSmallButton"))
        self.positionLabel = QtGui.QLabel(self.TIRFgroupBox)
        self.positionLabel.setGeometry(QtCore.QRect(210, 20, 81, 16))
        self.positionLabel.setObjectName(_fromUtf8("positionLabel"))
        self.positionText = QtGui.QLabel(self.TIRFgroupBox)
        self.positionText.setGeometry(QtCore.QRect(230, 40, 46, 14))
        self.positionText.setText(_fromUtf8(""))
        self.positionText.setObjectName(_fromUtf8("positionText"))
        self.EPIButton = QtGui.QPushButton(self.TIRFgroupBox)
        self.EPIButton.setGeometry(QtCore.QRect(10, 20, 41, 24))
        self.EPIButton.setObjectName(_fromUtf8("EPIButton"))
        self.TIRFButton = QtGui.QPushButton(self.TIRFgroupBox)
        self.TIRFButton.setGeometry(QtCore.QRect(160, 20, 41, 24))
        self.TIRFButton.setObjectName(_fromUtf8("TIRFButton"))
        self.rightLargeButton = QtGui.QPushButton(self.TIRFgroupBox)
        self.rightLargeButton.setGeometry(QtCore.QRect(128, 20, 31, 24))
        self.rightLargeButton.setObjectName(_fromUtf8("rightLargeButton"))
        self.leftSmallButton = QtGui.QPushButton(self.TIRFgroupBox)
        self.leftSmallButton.setGeometry(QtCore.QRect(85, 20, 20, 24))
        self.leftSmallButton.setObjectName(_fromUtf8("leftSmallButton"))
        self.moveGroupBox = QtGui.QGroupBox(self.TIRFgroupBox)
        self.moveGroupBox.setGeometry(QtCore.QRect(10, 50, 191, 51))
        self.moveGroupBox.setObjectName(_fromUtf8("moveGroupBox"))
        self.tirSpinBox = QtGui.QDoubleSpinBox(self.moveGroupBox)
        self.tirSpinBox.setGeometry(QtCore.QRect(10, 20, 71, 22))
        self.tirSpinBox.setDecimals(3)
        self.tirSpinBox.setMaximum(25.0)
        self.tirSpinBox.setSingleStep(0.001)
        self.tirSpinBox.setProperty("value", 21.0)
        self.tirSpinBox.setObjectName(_fromUtf8("tirSpinBox"))
        self.tirGoButton = QtGui.QPushButton(self.moveGroupBox)
        self.tirGoButton.setGeometry(QtCore.QRect(98, 19, 75, 24))
        self.tirGoButton.setObjectName(_fromUtf8("tirGoButton"))
        self.filterWheelGroupBox = QtGui.QGroupBox(Dialog)
        self.filterWheelGroupBox.setGeometry(QtCore.QRect(9, 126, 411, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterWheelGroupBox.sizePolicy().hasHeightForWidth())
        self.filterWheelGroupBox.setSizePolicy(sizePolicy)
        self.filterWheelGroupBox.setObjectName(_fromUtf8("filterWheelGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.filterWheelGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.filter1Button = QtGui.QPushButton(self.filterWheelGroupBox)
        self.filter1Button.setCheckable(True)
        self.filter1Button.setAutoExclusive(True)
        self.filter1Button.setObjectName(_fromUtf8("filter1Button"))
        self.horizontalLayout.addWidget(self.filter1Button)
        self.filter2Button = QtGui.QPushButton(self.filterWheelGroupBox)
        self.filter2Button.setCheckable(True)
        self.filter2Button.setAutoExclusive(True)
        self.filter2Button.setObjectName(_fromUtf8("filter2Button"))
        self.horizontalLayout.addWidget(self.filter2Button)
        self.filter3Button = QtGui.QPushButton(self.filterWheelGroupBox)
        self.filter3Button.setCheckable(True)
        self.filter3Button.setAutoExclusive(True)
        self.filter3Button.setObjectName(_fromUtf8("filter3Button"))
        self.horizontalLayout.addWidget(self.filter3Button)
        self.filter4Button = QtGui.QPushButton(self.filterWheelGroupBox)
        self.filter4Button.setCheckable(True)
        self.filter4Button.setAutoExclusive(True)
        self.filter4Button.setObjectName(_fromUtf8("filter4Button"))
        self.horizontalLayout.addWidget(self.filter4Button)
        self.filter5Button = QtGui.QPushButton(self.filterWheelGroupBox)
        self.filter5Button.setCheckable(True)
        self.filter5Button.setAutoExclusive(True)
        self.filter5Button.setObjectName(_fromUtf8("filter5Button"))
        self.horizontalLayout.addWidget(self.filter5Button)
        self.filter6Button = QtGui.QPushButton(self.filterWheelGroupBox)
        self.filter6Button.setCheckable(True)
        self.filter6Button.setAutoExclusive(True)
        self.filter6Button.setObjectName(_fromUtf8("filter6Button"))
        self.horizontalLayout.addWidget(self.filter6Button)
        self.okButton = QtGui.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(340, 200, 77, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.bfGroupBox = QtGui.QGroupBox(Dialog)
        self.bfGroupBox.setGeometry(QtCore.QRect(320, 10, 95, 111))
        self.bfGroupBox.setObjectName(_fromUtf8("bfGroupBox"))
        self.bfButton = QtGui.QPushButton(self.bfGroupBox)
        self.bfButton.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.bfButton.setObjectName(_fromUtf8("bfButton"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "HAL-4000 Miscellaneous Controls", None))
        self.TIRFgroupBox.setTitle(_translate("Dialog", "TIRF Control", None))
        self.leftLargeButton.setText(_translate("Dialog", "<<", None))
        self.rightSmallButton.setText(_translate("Dialog", ">", None))
        self.positionLabel.setText(_translate("Dialog", "Current Postion:", None))
        self.EPIButton.setText(_translate("Dialog", "EPI", None))
        self.TIRFButton.setText(_translate("Dialog", "TIRF", None))
        self.rightLargeButton.setText(_translate("Dialog", ">>", None))
        self.leftSmallButton.setText(_translate("Dialog", "<", None))
        self.moveGroupBox.setTitle(_translate("Dialog", "Move To", None))
        self.tirGoButton.setText(_translate("Dialog", "Go", None))
        self.filterWheelGroupBox.setTitle(_translate("Dialog", "Filter Wheel", None))
        self.filter1Button.setText(_translate("Dialog", "1", None))
        self.filter2Button.setText(_translate("Dialog", "2", None))
        self.filter3Button.setText(_translate("Dialog", "3", None))
        self.filter4Button.setText(_translate("Dialog", "4", None))
        self.filter5Button.setText(_translate("Dialog", "5", None))
        self.filter6Button.setText(_translate("Dialog", "6", None))
        self.okButton.setText(_translate("Dialog", "Ok", None))
        self.bfGroupBox.setTitle(_translate("Dialog", "BF Shutter", None))
        self.bfButton.setText(_translate("Dialog", "PushButton", None))

