# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stage.ui'
#
# Created: Thu Feb 27 11:24:34 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(438, 328)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(438, 328))
        Dialog.setMaximumSize(QtCore.QSize(438, 328))
        self.okButton = QtGui.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(360, 290, 75, 24))
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.leftSButton = QtGui.QPushButton(Dialog)
        self.leftSButton.setGeometry(QtCore.QRect(136, 131, 52, 66))
        self.leftSButton.setText(_fromUtf8(""))
        self.leftSButton.setObjectName(_fromUtf8("leftSButton"))
        self.leftLButton = QtGui.QPushButton(Dialog)
        self.leftLButton.setGeometry(QtCore.QRect(64, 131, 68, 66))
        self.leftLButton.setText(_fromUtf8(""))
        self.leftLButton.setObjectName(_fromUtf8("leftLButton"))
        self.rightSButton = QtGui.QPushButton(Dialog)
        self.rightSButton.setGeometry(QtCore.QRect(255, 132, 52, 66))
        self.rightSButton.setText(_fromUtf8(""))
        self.rightSButton.setObjectName(_fromUtf8("rightSButton"))
        self.rightLButton = QtGui.QPushButton(Dialog)
        self.rightLButton.setGeometry(QtCore.QRect(310, 132, 68, 66))
        self.rightLButton.setText(_fromUtf8(""))
        self.rightLButton.setObjectName(_fromUtf8("rightLButton"))
        self.upSButton = QtGui.QPushButton(Dialog)
        self.upSButton.setGeometry(QtCore.QRect(188, 79, 66, 52))
        self.upSButton.setText(_fromUtf8(""))
        self.upSButton.setObjectName(_fromUtf8("upSButton"))
        self.upLButton = QtGui.QPushButton(Dialog)
        self.upLButton.setGeometry(QtCore.QRect(188, 8, 66, 68))
        self.upLButton.setText(_fromUtf8(""))
        self.upLButton.setObjectName(_fromUtf8("upLButton"))
        self.downLButton = QtGui.QPushButton(Dialog)
        self.downLButton.setGeometry(QtCore.QRect(189, 252, 66, 68))
        self.downLButton.setText(_fromUtf8(""))
        self.downLButton.setObjectName(_fromUtf8("downLButton"))
        self.downSButton = QtGui.QPushButton(Dialog)
        self.downSButton.setGeometry(QtCore.QRect(189, 198, 66, 52))
        self.downSButton.setText(_fromUtf8(""))
        self.downSButton.setObjectName(_fromUtf8("downSButton"))
        self.posGroupBox = QtGui.QGroupBox(Dialog)
        self.posGroupBox.setGeometry(QtCore.QRect(260, 10, 171, 91))
        self.posGroupBox.setObjectName(_fromUtf8("posGroupBox"))
        self.yposText = QtGui.QLabel(self.posGroupBox)
        self.yposText.setGeometry(QtCore.QRect(55, 37, 111, 16))
        self.yposText.setText(_fromUtf8(""))
        self.yposText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yposText.setObjectName(_fromUtf8("yposText"))
        self.yposLabel = QtGui.QLabel(self.posGroupBox)
        self.yposLabel.setGeometry(QtCore.QRect(10, 36, 41, 20))
        self.yposLabel.setObjectName(_fromUtf8("yposLabel"))
        self.xposLabel = QtGui.QLabel(self.posGroupBox)
        self.xposLabel.setGeometry(QtCore.QRect(9, 17, 41, 20))
        self.xposLabel.setObjectName(_fromUtf8("xposLabel"))
        self.xposText = QtGui.QLabel(self.posGroupBox)
        self.xposText.setGeometry(QtCore.QRect(54, 17, 111, 16))
        self.xposText.setText(_fromUtf8(""))
        self.xposText.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xposText.setObjectName(_fromUtf8("xposText"))
        self.zeroButton = QtGui.QPushButton(self.posGroupBox)
        self.zeroButton.setGeometry(QtCore.QRect(90, 60, 71, 24))
        self.zeroButton.setObjectName(_fromUtf8("zeroButton"))
        self.homeButton = QtGui.QPushButton(Dialog)
        self.homeButton.setGeometry(QtCore.QRect(197, 140, 51, 51))
        self.homeButton.setObjectName(_fromUtf8("homeButton"))
        self.moveGroupBox = QtGui.QGroupBox(Dialog)
        self.moveGroupBox.setGeometry(QtCore.QRect(10, 200, 171, 111))
        self.moveGroupBox.setObjectName(_fromUtf8("moveGroupBox"))
        self.ymoveLabel = QtGui.QLabel(self.moveGroupBox)
        self.ymoveLabel.setGeometry(QtCore.QRect(10, 50, 41, 20))
        self.ymoveLabel.setObjectName(_fromUtf8("ymoveLabel"))
        self.xmoveLabel = QtGui.QLabel(self.moveGroupBox)
        self.xmoveLabel.setGeometry(QtCore.QRect(9, 21, 41, 20))
        self.xmoveLabel.setObjectName(_fromUtf8("xmoveLabel"))
        self.goButton = QtGui.QPushButton(self.moveGroupBox)
        self.goButton.setGeometry(QtCore.QRect(90, 80, 71, 24))
        self.goButton.setObjectName(_fromUtf8("goButton"))
        self.xmoveDoubleSpinBox = QtGui.QDoubleSpinBox(self.moveGroupBox)
        self.xmoveDoubleSpinBox.setGeometry(QtCore.QRect(50, 20, 111, 22))
        self.xmoveDoubleSpinBox.setDecimals(1)
        self.xmoveDoubleSpinBox.setMinimum(-100000.0)
        self.xmoveDoubleSpinBox.setMaximum(100000.0)
        self.xmoveDoubleSpinBox.setObjectName(_fromUtf8("xmoveDoubleSpinBox"))
        self.ymoveDoubleSpinBox = QtGui.QDoubleSpinBox(self.moveGroupBox)
        self.ymoveDoubleSpinBox.setGeometry(QtCore.QRect(50, 50, 111, 22))
        self.ymoveDoubleSpinBox.setDecimals(1)
        self.ymoveDoubleSpinBox.setMinimum(-100000.0)
        self.ymoveDoubleSpinBox.setMaximum(100000.0)
        self.ymoveDoubleSpinBox.setObjectName(_fromUtf8("ymoveDoubleSpinBox"))
        self.saveGroupBox = QtGui.QGroupBox(Dialog)
        self.saveGroupBox.setGeometry(QtCore.QRect(10, 10, 171, 111))
        self.saveGroupBox.setObjectName(_fromUtf8("saveGroupBox"))
        self.saveComboBox = QtGui.QComboBox(self.saveGroupBox)
        self.saveComboBox.setGeometry(QtCore.QRect(10, 20, 151, 22))
        self.saveComboBox.setObjectName(_fromUtf8("saveComboBox"))
        self.addButton = QtGui.QPushButton(self.saveGroupBox)
        self.addButton.setGeometry(QtCore.QRect(10, 50, 61, 23))
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.clearButton = QtGui.QPushButton(self.saveGroupBox)
        self.clearButton.setGeometry(QtCore.QRect(100, 50, 61, 23))
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.saveButton = QtGui.QPushButton(self.saveGroupBox)
        self.saveButton.setGeometry(QtCore.QRect(10, 80, 61, 23))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.loadButton = QtGui.QPushButton(self.saveGroupBox)
        self.loadButton.setGeometry(QtCore.QRect(100, 80, 61, 23))
        self.loadButton.setObjectName(_fromUtf8("loadButton"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "HAL-4000 Stage Control", None))
        self.okButton.setText(_translate("Dialog", "Ok", None))
        self.posGroupBox.setTitle(_translate("Dialog", "Current Position", None))
        self.yposLabel.setText(_translate("Dialog", "Y (um):", None))
        self.xposLabel.setText(_translate("Dialog", "X (um):", None))
        self.zeroButton.setText(_translate("Dialog", "Zero", None))
        self.homeButton.setText(_translate("Dialog", "Home", None))
        self.moveGroupBox.setTitle(_translate("Dialog", "Move To", None))
        self.ymoveLabel.setText(_translate("Dialog", "Y (um):", None))
        self.xmoveLabel.setText(_translate("Dialog", "X (um):", None))
        self.goButton.setText(_translate("Dialog", "Go", None))
        self.saveGroupBox.setTitle(_translate("Dialog", "Saved Positions", None))
        self.addButton.setText(_translate("Dialog", "Add", None))
        self.clearButton.setText(_translate("Dialog", "Clear", None))
        self.saveButton.setText(_translate("Dialog", "Save", None))
        self.loadButton.setText(_translate("Dialog", "Load", None))

