# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mosaic_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(437, 223)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(437, 223))
        Dialog.setMaximumSize(QtCore.QSize(437, 225))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pixLabel = QtWidgets.QLabel(self.groupBox)
        self.pixLabel.setObjectName("pixLabel")
        self.horizontalLayout_7.addWidget(self.pixLabel)
        self.pixDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.pixDoubleSpinBox.setDecimals(3)
        self.pixDoubleSpinBox.setMaximum(10.0)
        self.pixDoubleSpinBox.setSingleStep(0.01)
        self.pixDoubleSpinBox.setProperty("value", 0.16)
        self.pixDoubleSpinBox.setObjectName("pixDoubleSpinBox")
        self.horizontalLayout_7.addWidget(self.pixDoubleSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.horizCheckBox.setObjectName("horizCheckBox")
        self.verticalLayout.addWidget(self.horizCheckBox)
        self.vertCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.vertCheckBox.setObjectName("vertCheckBox")
        self.verticalLayout.addWidget(self.vertCheckBox)
        self.transCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.transCheckBox.setObjectName("transCheckBox")
        self.verticalLayout.addWidget(self.transCheckBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.objectiveLabel = QtWidgets.QLabel(self.groupBox_2)
        self.objectiveLabel.setObjectName("objectiveLabel")
        self.horizontalLayout.addWidget(self.objectiveLabel)
        self.objectiveLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.objectiveLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.objectiveLineEdit.setObjectName("objectiveLineEdit")
        self.horizontalLayout.addWidget(self.objectiveLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.magLabel = QtWidgets.QLabel(self.groupBox_2)
        self.magLabel.setObjectName("magLabel")
        self.horizontalLayout_2.addWidget(self.magLabel)
        self.magDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.magDoubleSpinBox.setMinimum(1.0)
        self.magDoubleSpinBox.setMaximum(200.0)
        self.magDoubleSpinBox.setSingleStep(0.01)
        self.magDoubleSpinBox.setProperty("value", 100.0)
        self.magDoubleSpinBox.setObjectName("magDoubleSpinBox")
        self.horizontalLayout_2.addWidget(self.magDoubleSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.xoffLabel = QtWidgets.QLabel(self.groupBox_2)
        self.xoffLabel.setObjectName("xoffLabel")
        self.horizontalLayout_3.addWidget(self.xoffLabel)
        self.xoffDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.xoffDoubleSpinBox.setMinimum(-10000.0)
        self.xoffDoubleSpinBox.setMaximum(10000.0)
        self.xoffDoubleSpinBox.setObjectName("xoffDoubleSpinBox")
        self.horizontalLayout_3.addWidget(self.xoffDoubleSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.yoffLabel = QtWidgets.QLabel(self.groupBox_2)
        self.yoffLabel.setObjectName("yoffLabel")
        self.horizontalLayout_4.addWidget(self.yoffLabel)
        self.yoffDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.yoffDoubleSpinBox.setMinimum(-10000.0)
        self.yoffDoubleSpinBox.setMaximum(10000.0)
        self.yoffDoubleSpinBox.setObjectName("yoffDoubleSpinBox")
        self.horizontalLayout_4.addWidget(self.yoffDoubleSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_6.addWidget(self.okButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Mosaic Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Mosaic"))
        self.pixLabel.setText(_translate("Dialog", "um per pixel"))
        self.horizCheckBox.setText(_translate("Dialog", "Flip Horiztonal"))
        self.vertCheckBox.setText(_translate("Dialog", "Flip Vertical"))
        self.transCheckBox.setText(_translate("Dialog", "Transpose"))
        self.groupBox_2.setTitle(_translate("Dialog", "Objective"))
        self.objectiveLabel.setText(_translate("Dialog", "Objective"))
        self.objectiveLineEdit.setText(_translate("Dialog", "100x"))
        self.magLabel.setText(_translate("Dialog", "Magnification"))
        self.xoffLabel.setText(_translate("Dialog", "X Offset"))
        self.yoffLabel.setText(_translate("Dialog", "Y Offset"))
        self.okButton.setText(_translate("Dialog", "Ok"))

