# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sections.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1283, 865)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sectionsDisplayFrame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectionsDisplayFrame.sizePolicy().hasHeightForWidth())
        self.sectionsDisplayFrame.setSizePolicy(sizePolicy)
        self.sectionsDisplayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sectionsDisplayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sectionsDisplayFrame.setObjectName("sectionsDisplayFrame")
        self.horizontalLayout.addWidget(self.sectionsDisplayFrame)
        self.sectionsWidget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectionsWidget.sizePolicy().hasHeightForWidth())
        self.sectionsWidget.setSizePolicy(sizePolicy)
        self.sectionsWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.sectionsWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sectionsWidget.setObjectName("sectionsWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.sectionsWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sectionsGroupBox = QtWidgets.QGroupBox(self.sectionsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sectionsGroupBox.sizePolicy().hasHeightForWidth())
        self.sectionsGroupBox.setSizePolicy(sizePolicy)
        self.sectionsGroupBox.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.sectionsGroupBox.setObjectName("sectionsGroupBox")
        self.verticalLayout_5.addWidget(self.sectionsGroupBox)
        self.sectionViewSettingsGroupBox = QtWidgets.QGroupBox(self.sectionsWidget)
        self.sectionViewSettingsGroupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sectionViewSettingsGroupBox.setObjectName("sectionViewSettingsGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.sectionViewSettingsGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.thresholdLabel = QtWidgets.QLabel(self.sectionViewSettingsGroupBox)
        self.thresholdLabel.setObjectName("thresholdLabel")
        self.gridLayout.addWidget(self.thresholdLabel, 1, 0, 1, 1)
        self.foregroundOpacitySlider = QtWidgets.QSlider(self.sectionViewSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foregroundOpacitySlider.sizePolicy().hasHeightForWidth())
        self.foregroundOpacitySlider.setSizePolicy(sizePolicy)
        self.foregroundOpacitySlider.setMaximum(100)
        self.foregroundOpacitySlider.setProperty("value", 50)
        self.foregroundOpacitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.foregroundOpacitySlider.setObjectName("foregroundOpacitySlider")
        self.gridLayout.addWidget(self.foregroundOpacitySlider, 4, 1, 1, 1)
        self.moveAllSectionsCheckBox = QtWidgets.QCheckBox(self.sectionViewSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveAllSectionsCheckBox.sizePolicy().hasHeightForWidth())
        self.moveAllSectionsCheckBox.setSizePolicy(sizePolicy)
        self.moveAllSectionsCheckBox.setObjectName("moveAllSectionsCheckBox")
        self.gridLayout.addWidget(self.moveAllSectionsCheckBox, 0, 0, 1, 1)
        self.foregroundOpacityLabel = QtWidgets.QLabel(self.sectionViewSettingsGroupBox)
        self.foregroundOpacityLabel.setObjectName("foregroundOpacityLabel")
        self.gridLayout.addWidget(self.foregroundOpacityLabel, 4, 0, 1, 1)
        self.showFeaturesCheckBox = QtWidgets.QCheckBox(self.sectionViewSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showFeaturesCheckBox.sizePolicy().hasHeightForWidth())
        self.showFeaturesCheckBox.setSizePolicy(sizePolicy)
        self.showFeaturesCheckBox.setObjectName("showFeaturesCheckBox")
        self.gridLayout.addWidget(self.showFeaturesCheckBox, 0, 1, 1, 1)
        self.backgroundLabel = QtWidgets.QLabel(self.sectionViewSettingsGroupBox)
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.gridLayout.addWidget(self.backgroundLabel, 2, 0, 1, 1)
        self.backgroundComboBox = QtWidgets.QComboBox(self.sectionViewSettingsGroupBox)
        self.backgroundComboBox.setObjectName("backgroundComboBox")
        self.backgroundComboBox.addItem("")
        self.gridLayout.addWidget(self.backgroundComboBox, 2, 1, 1, 1)
        self.thresholdSlider = QtWidgets.QSlider(self.sectionViewSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdSlider.sizePolicy().hasHeightForWidth())
        self.thresholdSlider.setSizePolicy(sizePolicy)
        self.thresholdSlider.setMaximum(100)
        self.thresholdSlider.setProperty("value", 50)
        self.thresholdSlider.setOrientation(QtCore.Qt.Horizontal)
        self.thresholdSlider.setObjectName("thresholdSlider")
        self.gridLayout.addWidget(self.thresholdSlider, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.sectionViewSettingsGroupBox)
        self.horizontalLayout.addWidget(self.sectionsWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sectionsGroupBox.setTitle(_translate("Form", "Sections"))
        self.sectionViewSettingsGroupBox.setTitle(_translate("Form", "Section View Settings"))
        self.thresholdLabel.setText(_translate("Form", "Threshold"))
        self.moveAllSectionsCheckBox.setText(_translate("Form", "Move All Sections"))
        self.foregroundOpacityLabel.setText(_translate("Form", "Section Opacity"))
        self.showFeaturesCheckBox.setText(_translate("Form", "Show Features"))
        self.backgroundLabel.setText(_translate("Form", "Background Type"))
        self.backgroundComboBox.setItemText(0, _translate("Form", "Mean"))

