# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'steve.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1148, 831)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.mosaicTab = QtWidgets.QWidget()
        self.mosaicTab.setObjectName("mosaicTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mosaicTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget.addTab(self.mosaicTab, "")
        self.sectionsTab = QtWidgets.QWidget()
        self.sectionsTab.setObjectName("sectionsTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.sectionsTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget.addTab(self.sectionsTab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1148, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuMosaic = QtWidgets.QMenu(self.menubar)
        self.menuMosaic.setObjectName("menuMosaic")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionSave_Positions = QtWidgets.QAction(MainWindow)
        self.actionSave_Positions.setObjectName("actionSave_Positions")
        self.actionSave_Mosaic = QtWidgets.QAction(MainWindow)
        self.actionSave_Mosaic.setObjectName("actionSave_Mosaic")
        self.actionSet_Working_Directory = QtWidgets.QAction(MainWindow)
        self.actionSet_Working_Directory.setObjectName("actionSet_Working_Directory")
        self.actionLoad_Mosaic = QtWidgets.QAction(MainWindow)
        self.actionLoad_Mosaic.setObjectName("actionLoad_Mosaic")
        self.actionDelete_Images = QtWidgets.QAction(MainWindow)
        self.actionDelete_Images.setObjectName("actionDelete_Images")
        self.actionLoad_Positions = QtWidgets.QAction(MainWindow)
        self.actionLoad_Positions.setObjectName("actionLoad_Positions")
        self.actionSave_Snapshot = QtWidgets.QAction(MainWindow)
        self.actionSave_Snapshot.setObjectName("actionSave_Snapshot")
        self.actionLoad_Movie = QtWidgets.QAction(MainWindow)
        self.actionLoad_Movie.setObjectName("actionLoad_Movie")
        self.actionLoad_Dax_By_Pattern = QtWidgets.QAction(MainWindow)
        self.actionLoad_Dax_By_Pattern.setObjectName("actionLoad_Dax_By_Pattern")
        self.actionAdjust_Contrast = QtWidgets.QAction(MainWindow)
        self.actionAdjust_Contrast.setObjectName("actionAdjust_Contrast")
        self.menuFile.addAction(self.actionSet_Working_Directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDelete_Images)
        self.menuFile.addAction(self.actionLoad_Movie)
        self.menuFile.addAction(self.actionLoad_Mosaic)
        self.menuFile.addAction(self.actionLoad_Positions)
        self.menuFile.addAction(self.actionSave_Mosaic)
        self.menuFile.addAction(self.actionSave_Positions)
        self.menuFile.addAction(self.actionSave_Snapshot)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuMosaic.addAction(self.actionAdjust_Contrast)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMosaic.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Steve"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mosaicTab), _translate("MainWindow", "Mosaic"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sectionsTab), _translate("MainWindow", "Sections"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuMosaic.setTitle(_translate("MainWindow", "Mosaic"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit (Ctrl+Q)"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.actionSave_Positions.setText(_translate("MainWindow", "Sav&e Positions"))
        self.actionSave_Positions.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionSave_Mosaic.setText(_translate("MainWindow", "Sa&ve Mosaic"))
        self.actionSave_Mosaic.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSet_Working_Directory.setText(_translate("MainWindow", "&Set Working Directory"))
        self.actionLoad_Mosaic.setText(_translate("MainWindow", "Load &Mosaic"))
        self.actionLoad_Mosaic.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionDelete_Images.setText(_translate("MainWindow", "&Delete Images"))
        self.actionDelete_Images.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionLoad_Positions.setText(_translate("MainWindow", "Load &Positions"))
        self.actionLoad_Positions.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionSave_Snapshot.setText(_translate("MainWindow", "Save S&napshot"))
        self.actionSave_Snapshot.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionLoad_Movie.setText(_translate("MainWindow", "&Load Movie"))
        self.actionLoad_Movie.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionLoad_Dax_By_Pattern.setText(_translate("MainWindow", "Load Dax By Pattern"))
        self.actionAdjust_Contrast.setText(_translate("MainWindow", "Adjust Contrast"))

