# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hazelnut.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sourceGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.sourceGroupBox.setObjectName("sourceGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.sourceGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.sourceLabel = QtWidgets.QLabel(self.sourceGroupBox)
        self.sourceLabel.setObjectName("sourceLabel")
        self.gridLayout.addWidget(self.sourceLabel, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.sourceGroupBox)
        self.transferGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.transferGroupBox.setObjectName("transferGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.transferGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.transferQueueMVC = TransferQueueMVC(self.transferGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transferQueueMVC.sizePolicy().hasHeightForWidth())
        self.transferQueueMVC.setSizePolicy(sizePolicy)
        self.transferQueueMVC.setObjectName("transferQueueMVC")
        self.gridLayout_2.addWidget(self.transferQueueMVC, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.transferGroupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.destinationGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destinationGroupBox.sizePolicy().hasHeightForWidth())
        self.destinationGroupBox.setSizePolicy(sizePolicy)
        self.destinationGroupBox.setObjectName("destinationGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.destinationGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.destinationLabel = QtWidgets.QLabel(self.destinationGroupBox)
        self.destinationLabel.setObjectName("destinationLabel")
        self.gridLayout_3.addWidget(self.destinationLabel, 0, 0, 1, 1)
        self.startPushButton = QtWidgets.QPushButton(self.destinationGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startPushButton.sizePolicy().hasHeightForWidth())
        self.startPushButton.setSizePolicy(sizePolicy)
        self.startPushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.startPushButton.setObjectName("startPushButton")
        self.gridLayout_3.addWidget(self.startPushButton, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.destinationGroupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSource_directory = QtWidgets.QAction(MainWindow)
        self.actionSource_directory.setObjectName("actionSource_directory")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSource = QtWidgets.QAction(MainWindow)
        self.actionSource.setObjectName("actionSource")
        self.actionDestination = QtWidgets.QAction(MainWindow)
        self.actionDestination.setObjectName("actionDestination")
        self.menuFile.addAction(self.actionSource)
        self.menuFile.addAction(self.actionDestination)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hazelnut"))
        self.sourceGroupBox.setTitle(_translate("MainWindow", "Source Directory"))
        self.sourceLabel.setText(_translate("MainWindow", "NA"))
        self.transferGroupBox.setTitle(_translate("MainWindow", "Transfer Queue"))
        self.destinationGroupBox.setTitle(_translate("MainWindow", "Destination"))
        self.destinationLabel.setText(_translate("MainWindow", "NA"))
        self.startPushButton.setText(_translate("MainWindow", "Start"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSource_directory.setText(_translate("MainWindow", "Source directory"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionSource.setText(_translate("MainWindow", "Source"))
        self.actionDestination.setText(_translate("MainWindow", "Destination"))

from transferQueue import TransferQueueMVC
